<style type="text/css">
	.editor{
		width:900px;
		height: 450px;
	}
	
</style>
<div class="header">
	<h1 class="page-title">添加<?php echo $this->sa['sl'];?></h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/home"><?php echo $this->bp->genActLink('article_index',$this->bp->act_link,$this->sa['sl'],array('s'=>$this->sa['st']));?></a> <span class="divider">/</span></li>
	<li class="active">添加<?php echo $this->sa['sl'];?></li>
    <li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
<form id="tab" name="createUser" method="post" action="" onsubmit="return checkArt();" enctype="multipart/form-data">
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<div class="btn-group"></div>
		</div>
		<div class="well">
			
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane active in" id="home">
						<div class="control-group" id="group-art_title">
							<label class="control-label" for="art_title">标题</label>
							<div class="controls">
								<input type="text" value="" id="art_title" name="art_title" class="span5">
                                <span class="help-inline" id="help-art_title"></span>
							</div>
						</div>				
						
						<div class="control-group" id="group-art_title_url">
							<label class="control-label" for="art_title_url">外部链接[慎用，需要带上http://]</label>
							<div class="controls">
								<input type="text" value="" id="art_title_url" name="art_title_url" class="span5">
                                <span class="help-inline" id="help-art_title_url"></span>
							</div>
						</div>	
						
						<div class="control-group" id="group-tag">
							<label class="control-label" for="tag">标签</label>
							<div class="controls">
								<input type="text" value="" id="tag" name="tag" class="span4">
                                <span class="help-inline" id="help-tag"></span>
							</div>
						</div>
						
						<?php if($this->sa['st'] == "def"):?>
							<div class="control-group" id="group-subclassid">
				              <label class="control-label" for="subclassid">新闻分类</label>
				              <div class="controls">
				                <select name="subclassid" id="subclassid">
				                <option value="60">--请选择分类--</option>
				                  <?php 
									if ($this->select_items)
									{
										foreach ($this->select_items as $val) {
											if($val['id'] == 60){//公司动态一级分类不显示
												continue;
											}
											echo "<option value=\"{$val['id']}\">{$val['name']}</option>";
										}
									}
								 ?>
				                </select>[<a href="/t/create?classid=11" target="_blank">添加分类</a>]
				                <span class="help-inline" id="help-subclassid"></span> </div>
				            </div>
						<?php endif;?>
						
						<div class="control-group" id="group-author">
							<label class="control-label" for="author">作者</label>
							<div class="controls">
								<input type="text" value="" id="author" name="author" class="span2">
                                <span class="help-inline" id="help-author"></span>
							</div>
						</div>
						
						<div class="control-group" id="group-art_from">
							<label class="control-label" for="art_from">来源</label>
							<div class="controls">
								<input type="text" value="" id="art_from" name="art_from" class="span2">
                                <span class="help-inline" id="help-art_from"></span>
							</div>
						</div>						
			            
                        <div class="control-group" id="group-commend">
                          <label class="control-label" for="commend">选择推荐</label>
                          <div class="controls">
                            <select name="commend" id="commend" class="span2">
                            <option value="0">推荐类型</option>
                            <option value="0">不推荐</option>
                            <option value="2">首页推荐</option>
                            <option value="1">一般推荐</option>
                            </select>
                          </div>
                        </div>
			
						<div class="control-group" id="group-fileField">
			              <label class="control-label" for="fileField">封面图片</label>
			              <div class="controls">
			                <input type="file" value="" name="fileField">
			                <span class="help-inline" id="help-fileField"></span> </div>
			            </div>
			
						<div class="control-group" id="group-art_content">
							<label class="control-label" for="art_content">内容</label>
							<div class="controls editor-container">							
								<textarea name="content" id="content" type="text" style="width: 570px;height: 200px;"></textarea>
								<span class="help-inline" id="help-art_content"></span>
							</div>
						</div>
						
						
				</div>
			</div>

		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>
<script src="/ueditor/ueditor.all.min.js"></script>
<script src="/ueditor/ueditor.config.js"></script>