<style type="text/css">
	.editor{
		width:900px;
		height: 450px;
	}
	
</style>
<div class="header">
	<h1 class="page-title">编辑<?php echo $this->sa['sl'];?></h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/home"><?php echo $this->bp->genActLink('article_index',$this->bp->act_link,$this->sa['sl'],array('s'=>$this->sa['st']));?></a> <span class="divider">/</span></li>
	<li class="active">编辑<?php echo $this->sa['sl'];?></li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
<form id="tab" name="createUser" method="post" action="" onsubmit="return checkArt();" enctype="multipart/form-data">
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<input type="hidden" name="file_id" value="<?php echo $this->fileInfo->file_id;?>"/>
			<div class="btn-group"></div>
		</div>
		<div class="well">
			
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane active in" id="home">
						<div class="control-group" id="group-art_title">
							<label class="control-label" for="art_title">标题</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['art_title'];?>" id="art_title" name="art_title" class="span6">
                                <span class="help-inline" id="help-art_title"></span>
							</div>
						</div>						
						
						<div class="control-group" id="group-art_title_url">
							<label class="control-label" for="art_title_url">外部链接[慎用，需要带上http://]</label>
							<div class="controls">
								<input type="text" value="<?php if(isset($this->row['art_title_url'])){echo $this->row['art_title_url'];}?>" id="art_title_url" name="art_title_url" class="span5">
                                <span class="help-inline" id="help-art_title_url"></span>
							</div>
						</div>						
						
						<div class="control-group" id="group-tag">
							<label class="control-label" for="tag">标签</label>
							<div class="controls">
								<input type="text" value="<?php if(isset($this->row['tag'])){echo $this->row['tag'];}?>" id="tag" name="tag" class="span4">
                                <span class="help-inline" id="help-tag"></span>
							</div>
						</div>
						<?php if($this->sa['st'] == "def"):?>
							<div class="control-group" id="group-subclassid">
				              <label class="control-label" for="subclassid">新闻分类</label>
				              <div class="controls">
				                <select name="subclassid" id="subclassid">
				                <option value="60">--请选择分类--</option>
				                  <?php 
										if ($this->select_items)
										{
											foreach ($this->select_items as $val) {
												if($val['id'] == 60){//公司动态一级分类不显示
													continue;
												}
												echo "<option value=\"{$val['id']}\"";
												if ($this->row['subclassid']==$val['id']) echo ' selected="true"';
												echo ">{$val['name']}</option>";
											}
										}
										?>
				                </select>
				                <span class="help-inline" id="help-subclassid"></span> </div>
				            </div>
						<?php endif;?>
						
						<div class="control-group" id="group-author">
							<label class="control-label" for="author">作者</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['author'];?>" id="author" name="author" class="span2">
                                <span class="help-inline" id="help-author"></span>
							</div>
						</div>
						
						<div class="control-group" id="group-art_from">
							<label class="control-label" for="art_from">来源</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['art_from'];?>" id="art_from" name="art_from" class="span2">
                                <span class="help-inline" id="help-art_from"></span>
							</div>
						</div>
						
                        <div class="control-group" id="group-commend">
                          <label class="control-label" for="commend">选择推荐</label>
                          <div class="controls">
                            <select name="commend" id="commend" class="span2">
                            <option value="0">推荐类型</option>
                            <option value="0" <?php echo $this->row['commend']==0?' selected="true"':'';?>>不推荐</option>
                            <option value="2" <?php echo $this->row['commend']==2?' selected="true"':'';?>>首页推荐</option>
                            <option value="1" <?php echo $this->row['commend']==1?' selected="true"':'';?>>一般推荐</option>
                            </select>
                          </div>
                        </div>		
						
						<div class="control-group" id="group-fileField">
			              <label class="control-label" for="fileField">更换封面图片</label>
			              <div class="controls">
			                <input type="file" value="" name="fileField">
			                <span class="help-inline" id="help-fileField"></span> </div>
			            </div>
						
						<div class="control-group" id="group-fileField">
			              <label class="control-label" for="fileField">&nbsp;</label>
			              <div class="controls">
			              	<?php if(isset($this->fileInfo->thumb)):?>
								<img src="<?php echo $this->fileInfo->thumb;?>">
							<?php endif;?>
						  </div>
			            </div>
						
						<div class="control-group" id="group-art_content">
							<label class="control-label" for="art_content">内容</label>
							<div class="controls editor-container">							
								<textarea name="content" id="content" type="text" style="width: 570px;height: 200px;"><?php echo $this->row['art_content']?></textarea>
								<span class="help-inline" id="help-art_content"></span>
							</div>
						</div>
						
						
				</div>
			</div>

		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>
<script src="/ueditor/ueditor.all.min.js"></script>
<script src="/ueditor/ueditor.config.js"></script>