<div class="header">
	<h1 class="page-title">编辑会员等级</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><?php echo $this->bp->genActLink('level_index',$this->bp->act_link,'会员等级列表');?> <span class="divider">/</span></li>
	<li class="active">编辑会员等级</li>
</ul>

<div class="container-fluid">
	<?php echo $this->partial('partials/flashMsg.phtml');?>
	<div class="row-fluid">
<form id="tab" name="createAccess" method="post" action="" onsubmit="return checkLevel();" enctype="multipart/form-data">
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<div class="btn-group"></div>
		</div>
		<div class="well">
			
			
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane active in" id="home">
						<div class="control-group" id="group-level_name">
							<label class="control-label" for="level_name">等级名称</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['level_name']?>" id="level_name" name="level_name" class="input-xlarge">
                                <span class="help-inline" id="help-level_name"></span>
							</div>
						</div>
						<div class="control-group" id="group-level_point">
							<label class="control-label" for="level_point">等级积分</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['level_point']?>" id="level_point" name="level_point" class="input-xlarge">
                                <span class="help-inline" id="help-level_point"></span>
							</div>
						</div>
						
						<div class="control-group" id="group-fileField">
			              <label class="control-label" for="fileField">等级图标(Icon)</label>
						  <?php if($this->row['level_icon']){ ?>
				                <div id="pics">
				                <?php
				                echo "<a href=\"".$this->row['level_icon']."\"  title=\"缩略图\" target='_blank'><img src=\"".$this->row['level_icon']."\" alt=\"缩略图\"/></a>\n";
				                ?>
				                </div>
				          <?php } ?>
			              <div class="controls">
			                <input type="file" value="" name="fileField">
			                <span class="help-inline" id="help-fileField"></span> </div>
			            </div>
						
						
						<div class="control-group" id="group-content">
							<label class="control-label" for="content">等级描述</label>
							<div class="controls editor-container">							
								<textarea name="level_desc" id="level_desc" type="text" class="editor"><?php echo $this->row['level_desc']?></textarea>
								<span class="help-inline" id="help-content"></span>
							</div>
						</div>
						
				</div>
			</div>

		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>