<div class="header">
	<h1 class="page-title">会员等级列表</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li class="active">会员等级列表</li>
	<li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>

<div class="container-fluid">
	<?php echo $this->partial('partials/flashMsg.phtml');?>
	<div class="row-fluid">	
    		<div id="helpcontroller" class="collapse"></div>
		<div class="btn-toolbar">
			<?php echo $this->bp->genActLink('level_create',$this->bp->act_add,'添加会员等级');?>
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>等级名称</th>
						<th>等级描述</th>
						<th>等级积分</th>
						<th>等级图标(Icon)</th>
						<th style="width: 50px;">改/删</th>
					</tr>
				</thead>
				<tbody>
				
				
				<?php 
					if($this->rows):
						foreach($this->rows as $val):
				?>
						<tr id="level_<?php echo $val['level_id'];?>">
							<td><?php echo $val['level_id'];?></td>
							<td><?php echo $val['level_name'];?></td>
							<td><?php echo $val['level_desc'];?></td>
							<td><?php echo $val['level_point'];?></td>
							<td><img src="<?php echo $val['level_icon'];?>" width="50px" height="50px"/></td>
							<td>
							<?php echo $this->bp->genActLink('level_edit',$this->bp->act_edit,'',array('level_id'=>$val['level_id']));?>
							 &nbsp;
							<?php echo $this->bp->genActLink('level_delete',$this->bp->act_del,'',array('del_id'=>$val['level_id']));?>
							</td>
						</tr>
				<?php	
						endforeach; 
					endif;
				?>
				
				
				
				<!--Display List-->	
				</tbody>
			</table>
		</div>
		
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<script type="text/javascript">
			  function triggerDel(del_id)
			  {
			   		$("#delid").click(function(){
						$.getJSON('/level/delete?level_id='+del_id,function(data){
							if (data.req=="ok")
		                     {
		                    	 $('#level_'+del_id).hide();
		                     }
						});
					});		
			  }
			   
		   </script>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除会员等级</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>是否删除选定的会员等级？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="delid" data-dismiss="modal">确定</button>
			</div>
		</div>
		<?php 
		echo $this->partial('partials/homeFooter.phtml');
		?>
	</div>
</div>