<div class="header">
	<h1 class="page-title">编辑广告位</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/ads">广告位列表</a> <span class="divider">/</span></li>
	<li class="active">编辑广告位</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
<form id="tab" name="editAds" method="post" action="/ads/edit?id=<?php echo $this->row['id'];?>" >
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane active in" id="home">
				         <div class="control-group" id="group-title">
							<label class="control-label" for="title">位置名称</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['title'];?>" id="title" placeholder="请输入名称" name="title" class="input-xlarge">
                                <span class="help-inline" id="help-code"></span>
							</div>
						 </div>
						 <div class="control-group" id="group-adType">
							<label class="control-label" for="adType">所属系统</label>
							<div class="controls">
								微站 <input type="radio" value="1" id="adType_1" name="adType" <?php echo $this->row['adType']==1?'checked="checked"':'';?>>
								微商城 <input type="radio" value="2" id="adType_2" name="adType" <?php echo $this->row['adType']==2?'checked="checked"':'';?>>
                                <span class="help-inline" id="help-code"></span>
							</div>
						 </div>
				</div>
			</div>
		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>