<div class="header">
	<h1 class="page-title">微信菜单</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li class="active">菜单列表</li> => [<b>请注意：</b>每次修改菜单，请提交到微信]
		<li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>

<div class="container-fluid">
	   <div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
	    <?php 
    	if ($this->message)
    	{
    		echo "<div class=\"alert alert-{$this->message->alert}\">
    		<a class=\"close\" data-dismiss=\"alert\">×</a>
    		<strong>{$this->message->title}</strong>  {$this->message->message}</div>";
    	}
        
        function generate_news_string($news){
            if($news['news_id'] > 0){
                $flags=array();
                if(isset($news['pic_url'])){
                    array_push($flags,"图");
                }else{
                    array_push($flags,"文");
                }
                if($news['type'] == 1){
                    array_push($flags,"多");
                }else{
                    array_push($flags,"单");
                }
                $flags = "[" . implode(",",$flags) . "]";
                return $flags.$news['title'];
            }
            else{
                return "#";
            }
}
    	?>
			
		</div>
		<?php if(!$this->userData['appId'] || !$this->userData['appSecret']){ ?>
		<div style="margin-top:10px;"><div class="well"><center><b>请您先进行 <font color=red><a href="/menu/config">自定义菜单通信配置</a></font> ，配置通过才能继续操作！</b></center></div></div>
		<?php }else{?>
		<div class="btn-toolbar">
		<a href="/menu/create" class="btn btn-primary"><i class="icon-plus"></i> 添加菜单</a>
		<a href="/menu/refresh" class="btn btn-primary"><i class="icon-retweet"></i> 菜单提交到微信</a>
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="6%">#</th>
						<th>名称</th>
						<th>消息素材编号</th>
						<th style="width: 50px;">改/删</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
					foreach ($this->rows as $val) {
				?>
					<tr id="menu_<?php echo $val['id'];?>">
						<td><?php 
						echo "<input type=\"checkbox\" name=\"id[]\" id=\"id\" value=\"{$val['id']}\"";
						?></td>
						<td><?php echo $val['menuname'];?>
						<?php 
						if (isset($val['next']) && count($val['next'])>5) echo '<font color="red"> 当前'.count($val['next']).'子菜单，最多只能是5个子菜单，请移除多出的菜单</font>';
						?>
						</td>
						<td><?php echo generate_news_string($val);?></td>
						<td>						
						<?php echo $this->bp->genActLink('menu_edit',$this->bp->act_edit,'修改',array('id'=>$val['id']));?>
						 &nbsp;
						<?php echo $this->bp->genActLink('menu_delete',$this->bp->act_del,'',array('del_id'=>$val['id']));?></td>
					</tr>
					<?php 
					if (isset($val['next']))
					{
						foreach ($val['next'] as $nVal)
						{
						?>
						<tr id="menu_<?php echo $nVal['id'];?>">
						<td><?php 
						echo "<input type=\"checkbox\" name=\"id[]\" id=\"id\" value=\"{$nVal['id']}\"";
						?></td>
						<td>&nbsp;&nbsp;&nbsp;&nbsp;|- <?php echo $nVal['menuname'];?></td>
						<td><?php echo generate_news_string($nVal);?></td> 
                        <td>
						<?php echo $this->bp->genActLink('menu_edit',$this->bp->act_edit,'修改',array('id'=>$nVal['id']));?>
						 &nbsp;
						<?php echo $this->bp->genActLink('menu_delete',$this->bp->act_del,'',array('del_id'=>$nVal['id']));?>
						</td>
					    </tr>
						<?php
						}
					}
					?>
					<?php 
					  }
			       }
					?>
				</tbody>
			</table>
		</div>
        <script type="text/javascript">		 
		 function triggerDel(del_id)
	     {
	   		$("#remove").click(function(){
				 
				  $.post('/menu/delete?id='+del_id,{'id':del_id},function(n){
                    typeof n == 'string' && (n = $.parseJSON(n));
                    if (n && n.code == 'ok') {
                        for(var i=0;i<n.data.length;i++){
                            $('#menu_'+n.data[i]).hide();
                        }
                    }else{
                        msg_alert("删除菜单出错!");/*lwq:alert统一换成界面出错提示*/
                    }
               },'json');
				
			});		
	    }
	    </script>
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除菜单</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>确认删除当前选定的菜单以及子菜单？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="remove" data-dismiss="modal">确认</button>
			</div>
		</div>
		<?php 
    	}
		echo $this->partial('partials/homeFooter.phtml');
		?>
	</div>
</div>
