<div class="header">
  <h1 class="page-title">添加商品</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/home">首页</a> <span class="divider">/</span></li>
  <li><a href="/commodity">商品列表</a> <span class="divider">/</span></li>
  <li class="active">添加商品</li>
  <li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>
<div class="container-fluid">
  <div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
    <?php 
    if (($this->userData['commodityCount'] > $this->count || $this->userData['commodityCount']==0) && empty($this->action)){
       //if (!$this->alipay) echo '<div class="alert alert-warning" style="margin-top:10px;"><center><b><font color="red">支付宝未绑定测试，建议测试支付宝支付</font> >>  <a href="/users/config">配置支付宝</a></b></center></div>';
    ?>
    <form id="tab" name="commodityCreate" method="post" action=""  onsubmit="return clickForm();" enctype="multipart/form-data">
      <div class="btn-toolbar">
        <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
        <input type="hidden" name="goods_id" id="goods_id" value="0" /> <!--初始化商品ID为0-->
        <div class="btn-group"></div>
      </div>
      <div class="well">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#home" data-toggle="tab">基础配置</a></li>
          <li><a href="#profile" data-toggle="tab">描述内容</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
          <div class="tab-pane active in" id="home">
            <div class="control-group" id="group-shop">
              <label class="control-label" for="shop">门店名称</label>
              <div class="controls">
                <select name="shop" id="shop">
                <option value="">请选择门店</option>
                  <?php 
						if ($this->shop)
						{
							foreach ($this->shop as $val) {
                                if($this->user->power==1 && in_array($val['id'],$this->userShop))
                                {
								   echo "<option value=\"{$val['id']}\">{$val['shopname']}</option>";
                                }
                                if ($this->user->power==2)
                                {
                                    echo "<option value=\"{$val['id']}\">{$val['shopname']}</option>";
                                }
							}
						}
						?>
                </select>[<a href="/shop/create" target="_blank">添加门店</a>]
                <span class="help-inline" id="help-shop"></span> </div>
            </div>
			
			<div class="control-group" id="group-brandID">
              <label class="control-label" for="brandID">商品品牌</label>
              <div class="controls">
                <select name="brandID" id="brandID">
                <option value="0">请选择品牌</option>
                  <?php 
						if ($this->brands)
						{
							foreach ($this->brands as $val) {
								echo "<option value=\"{$val['brand_id']}\"";
								echo ">{$val['brand_name']}</option>";
							}
						}
						?>
                </select>[<a href="/brand/create" target="_blank">添加分类</a>]
                <span class="help-inline" id="help-brandID"></span> </div>
            </div>
			
			
            <div class="control-group" id="group-cateID">
              <label class="control-label" for="cateID">商品分类</label>
              <div class="controls">
                <select name="cateID" id="cateID">
                <option value="">请选择分类</option>
                  <?php 
						if ($this->select_items)
						{
							foreach ($this->select_items as $val) {
								echo "<option value=\"{$val['id']}\">{$val['name']}</option>";
							}
						}
						?>
                </select>[<a href="/t/create?classid=10" target="_blank">添加分类</a>]
                <span class="help-inline" id="help-cateID"></span> </div>
            </div>
            <div class="control-group" id="group-fileField">
              <label class="control-label" for="fileField">缩略图</label>
              <div class="controls">
                <input type="file" value="" name="fileField">
                <span class="help-inline" id="help-fileField"></span> </div>
            </div>
            <div class="control-group" id="group-wares">
              <label class="control-label" for="wares">商品名称</label>
              <div class="controls">
                <input type="text" value="" name="wares" id="wares" class="span3">
                <span class="help-inline" id="help-wares"></span> </div>
            </div>
            <div class="control-group" id="group-price">
              <label class="control-label" for="price">价格</label>
              <div class="controls">
                <input type="text" value="" name="price" id="price" class="span3">
                <span class="help-inline" id="help-price"></span> </div>
            </div>
            <div class="control-group" id="group-rebate">
              <label class="control-label" for="rebate">折扣价</label>
              <div class="controls">
                <input type="text" value="" name="rebate" id="rebate" class="span3">
                <span class="help-inline" id="help-rebate"></span> </div>
            </div>
			
			<!--此处添加运费一栏-->
			<div class="control-group" id="group-rebate">
              <label class="control-label" for="rebate">运费</label>
              <div class="controls">
			  	<select name="feeby" id="feeby">
                <option value="">---请选择---</option>
                <option value="buyer">买家承担运费(消费者)</option>
				<option value="seller">卖家承担运费(商户)</option>   
                </select>
                平邮 <input type="text" value="" name="mail" id="mail" class="input-small">
				EMS <input type="text" value="" name="ems" id="ems" class="input-small">
				物流 <input type="text" value="" name="wuliu" id="wuliu" class="input-small">
                <span class="help-inline" id="help-rebate"></span> </div>
            </div>
			
			
           <!-- <div class="control-group" id="group-order">
              <label class="control-label" for="order">排序</label>
              <div class="controls">
                <input type="text" value="" name="order" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-order"></span> </div>
            </div> -->
            <div class="control-group" id="group-repertory">
              <label class="control-label" for="repertory">库存量</label>
              <div class="controls">
                <input type="text" value="" name="repertory" id="repertory" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-repertory"></span> </div>
            </div>
            <div class="control-group" id="group-sold">
              <label class="control-label" for="sold">售出数量</label>
              <div class="controls">
                <input type="text" value="0" name="sold" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-sold"></span> </div>
            </div>
            
			<!--此处插入文件上传模板-->
			<?php echo $this->partial('partials/uploadify_create.phtml');?>
			
            <div class="control-group" id="group-added">
              <label class="control-label" for="added">是否上架</label>
              <div class="controls"> 是
                <input type="radio" value="1" name="added" >
                否
                <input type="radio" value="0" name="added" checked>
              </div>
            </div>
            <div class="control-group" id="group-commend">
              <label class="control-label" for="commend">选择推荐</label>
              <div class="controls">
                <select name="commend" id="commend" class="span2">
                <option value="0">推荐类型</option>
                <option value="0">不推荐</option>
                <option value="3">首页幻灯推荐</option>
                <option value="2">首页推荐</option>
                <option value="1">一般推荐</option>
                </select>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="profile">
            <div class="control-group" id="group-weixin">
              <label class="control-label" for="weixin">微信/产品描述[不超过500字]</label>
              <div class="controls">
                <textarea rows="4" class="span7" id="weixin" name="weixin"></textarea>
                <span class="help-inline" id="help-weixin"></span> </div>
            </div>
            <div class="control-group" id="group-content">
              <label class="control-label" for="content">图文详情<br><span style="font-size:8px;">(小贴士：1.请不要将word等文档里的内容直接Copy至这里，以免排版乱掉<br>2.大图片建议尺寸：720像素 × 400像素，图片我们不建议过大，以免占用手机用户过多流量)</span></label>
              <div class="controls editor-container-max">	
                <textarea class="editor-max" id="content" name="content"></textarea>
                <span class="help-inline" id="help-content"></span> </div>
            </div>
          </div>
        </div>
      </div>
      

<script type="text/javascript">
a2a_linkname = document.title;
a2a_linkurl = "";

$(document).ready(function(){    
    //定时保存用户填写的商品信息
    setInterval(ajaxPost,180000);    
});

function ajaxPost()
{
    if($("#wares").val().length == 0){//没填写商品名无需提交
        return false;
    }
    $.ajax({
      type: "POST",
      url: "/commodity/create",
      dataType: "json",
      data: $("#tab").serializeArray(),
      success: function (result) {
         if(result.req == "ok"){
             $("#goods_id").val(result.goods_id);
         }
      }
   });
}
</script>
    </form>
      <?php 
       }else{
            echo '<div style="margin:10px;"><div class="well"><center><b>您最大可加商品数为 <font color=red>'.$this->userData['commodityCount'].'</font> ，请联系管理员或者通过‘<a href="/answers/create">有问必答</a>’平台升级更多商品数！</b></center></div></div>';
        }
      echo $this->partial('partials/homeFooter.phtml');
      ?>
  </div>
</div>