<style type="text/css">
	ul.spec{
		overflow: hidden;
	}
	ul.spec li{
		display: inline-block;
	}
	ul.spec li.lbl{
		width: 10%;
		line-height: 30px;
	}
	.more_spec{
		padding-left:25px;
	}
</style>
<div class="header">
	<h1 class="page-title">编辑商品</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/commodity">商品列表</a> <span class="divider">/</span></li>
	<li class="active">编辑商品</li>
    <li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
<form id="tab" name="commodityCreate" method="post" onsubmit="return clickForm();" action="?id=<?php echo $this->row['id'];?>" enctype="multipart/form-data">
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#home" data-toggle="tab">基础配置</a></li>
				<li><a href="#profile" data-toggle="tab">描述内容</a></li>
				<li><a href="#pic" data-toggle="tab">商品图片</a></li>
				<li><a href="#spec" data-toggle="tab">商品属性/规格</a></li>
			</ul>
			<div id="myTabContent" class="tab-content">
          <div class="tab-pane active in" id="home">
            <div class="control-group" id="group-shop">
              <label class="control-label" for="shop">门店名称</label>
              <div class="controls">
                <select name="shop" id="shop">
                <option value="">请选择门店</option>
                  <?php 
						if ($this->shop)
						{
							foreach ($this->shop as $val) {
								echo "<option value=\"{$val['id']}\"";
								if ($this->row['shop']==$val['id']) echo ' selected="true"';
								echo ">{$val['shopname']}</option>";
							}
						}
						?>
                </select>
                <span class="help-inline" id="help-shop"></span> </div>
            </div>
			
			<div class="control-group" id="group-brandID">
              <label class="control-label" for="brandID">商品品牌</label>
              <div class="controls">
                <select name="brandID" id="brandID">
                <option value="0">请选择品牌</option>
                  <?php 
						if ($this->brands)
						{
							foreach ($this->brands as $val) {
								echo "<option value=\"{$val['brand_id']}\"";
								if ($this->row['brandID']==$val['brand_id']) echo ' selected="true"';
								echo ">{$val['brand_name']}</option>";
							}
						}
						?>
                </select>
                <span class="help-inline" id="help-brandID"></span> </div>
            </div>
			
            <div class="control-group" id="group-cateID">
              <label class="control-label" for="cateID">商品分类</label>
              <div class="controls">
                <select name="cateID" id="cateID">
                <option value="">请选择分类</option>
                  <?php 
						if ($this->select_items)
						{
							foreach ($this->select_items as $val) {
								echo "<option value=\"{$val['id']}\"";
								if ($this->row['cateID']==$val['id']) echo ' selected="true"';
								echo ">{$val['name']}</option>";
							}
						}
						?>
                </select>
                <span class="help-inline" id="help-cateID"></span> </div>
            </div>
            <div class="control-group" id="group-fileField">
              <label class="control-label" for="fileField">缩略图</label>
            <?php if($this->row['thumb']){ ?>
                <div id="pics">
                <?php
                echo "<a href=\"".$this->row['thumb']."\" rel=\"[gall1]\" title=\"缩略图\"><img src=\"".$this->row['thumb']."\" alt=\"缩略图\" width=\"80\" height=\"60\" /></a>\n";
                ?>
                </div>
            <?php } ?>
              <div class="controls">
                <input type="file" class="input-file" name="fileField" id="fileField" />
                <span class="help-inline" id="help-fileField"></span> 
                </div>
            </div>
            <div class="control-group" id="group-wares">
              <label class="control-label" for="wares">商品名称</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['name'];?>" name="wares" id="wares" class="span3">
                <span class="help-inline" id="help-wares"></span> </div>
            </div>
            <div class="control-group" id="group-price">
              <label class="control-label" for="price">价格</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['price'];?>" name="price" id="price" class="span3">
                <span class="help-inline" id="help-price"></span> </div>
            </div>
            <div class="control-group" id="group-rebate">
              <label class="control-label" for="rebate">折扣价</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['rebate'];?>" name="rebate" id="rebate" class="span3">
                <span class="help-inline" id="help-rebate"></span> </div>
            </div>
			
			<!--此处添加运费一栏-->
			<div class="control-group" id="group-rebate">
              <label class="control-label" for="rebate">运费</label>
              <div class="controls">
			  	<select name="feeby" id="feeby">
                <option value="">---请选择---</option>
                <option value="buyer" <?php if($this->row['freight'] && $this->row['freight']['feeby'] == "buyer"){echo "selected=\"selected\"";}?>>买家承担运费(消费者)</option>
				<option value="seller" <?php if($this->row['freight'] && $this->row['freight']['feeby'] == "seller"){echo "selected=\"selected\"";}?>>卖家承担运费(商户)</option>   
                </select>
                平邮 <input type="text" value="<?php if($this->row['freight']) echo $this->row['freight']['mail']; ?>" name="mail" id="mail" class="input-small">
				EMS <input type="text" value="<?php if($this->row['freight']) echo $this->row['freight']['ems']; ?>" name="ems" id="ems" class="input-small">
				物流 <input type="text" value="<?php if($this->row['freight']) echo $this->row['freight']['wuliu']; ?>" name="wuliu" id="wuliu" class="input-small">
                <span class="help-inline" id="help-rebate"></span> </div>
            </div>
			
			
            <!-- <div class="control-group" id="group-order">
              <label class="control-label" for="order">排序</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['order'];?>" name="order" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-order"></span> </div>
            </div> -->
            <div class="control-group" id="group-repertory">
              <label class="control-label" for="repertory">库存量</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['repertory'];?>" name="repertory" id="repertory" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-repertory"></span> </div>
            </div>
            <div class="control-group" id="group-sold">
              <label class="control-label" for="sold">售出数量</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['sold'];?>" name="sold" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-sold"></span> </div>
            </div>		
            
            <div class="control-group" id="group-added">
              <label class="control-label" for="added">是否上架</label>
              <div class="controls"> 是
                <input type="radio" value="1" name="added"  <?php echo $this->row['added']==1?'checked':'';?> >
                否
                <input type="radio" value="0" name="added"  <?php echo $this->row['added']==0?'checked':'';?>>
              </div>
            </div>
            <div class="control-group" id="group-commend">
              <label class="control-label" for="commend">选择推荐</label>
              <div class="controls">
                <select name="commend" id="commend" class="span2">
                <option value="0">推荐类型</option>
                <option value="0" <?php echo $this->row['commend']==0?' selected="true"':'';?>>不推荐</option>
                <option value="3" <?php echo $this->row['commend']==3?' selected="true"':'';?>>首页幻灯推荐</option>
                <option value="2" <?php echo $this->row['commend']==2?' selected="true"':'';?>>首页推荐</option>
                <option value="1" <?php echo $this->row['commend']==1?' selected="true"':'';?>>一般推荐</option>
                </select>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="profile">
            <div class="control-group" id="group-weixin">
              <label class="control-label" for="weixin">微信/产品描述[不超过500字]</label>
              <div class="controls">
                <textarea rows="4" class="span7" id="weixin" name="weixin"><?php echo htmlspecialchars_decode(stripcslashes($this->row['weixin']));?></textarea>
                <span class="help-inline" id="help-weixin"></span> </div>
            </div>
            <div class="control-group" id="group-content">
              <label class="control-label" for="content">图文详情<br><span style="font-size:8px;">(小贴士：1.请不要将word等文档里的内容直接Copy至这里，以免排版乱掉<br>2.大图片建议尺寸：720像素 × 400像素，图片我们不建议过大，以免占用手机用户过多流量)</span></label>
              <div class="controls editor-container-max">	
                <textarea class="editor-max" id="content" name="content"><?php echo htmlspecialchars_decode(stripcslashes($this->row['content']));?></textarea>
                <span class="help-inline" id="help-content"></span> </div>
            </div>
          </div>
		  
		  <!--此处插入文件上传模板-->
		  <?php echo $this->partial('partials/uploadify_edit.phtml')?>
		  
		  
		  <div class="tab-pane fade" id="spec">
			<div class="more_spec"><input type="button" class="btn" value="+添加/编辑/删除规格"> (小贴士:刷新此页面更新规格列表)</div>
			<?php echo $this->specList;?>
          </div>
		  
		  
		  
		  
        </div>
		</div>
		 
<script type="text/javascript" charset="utf-8" src="/js/jquery-foxibox-0.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  var prodClassId = "<?php echo $row->cateID?>";
  //添加更多规格
  $(".more_spec .btn").click(function(){
  		openwindow("/attribute/index?prod_class="+prodClassId,"_target",800,600);
  });
  
});


function openwindow(url,name,iWidth,iHeight)
  {
	  var url;                                 //转向网页的地址;
	  var name;                           //网页名称，可为空;
	  var iWidth;                          //弹出窗口的宽度;
	  var iHeight;                        //弹出窗口的高度;
	  var iTop = (window.screen.availHeight-30-iHeight)/2;       //获得窗口的垂直位置;
	  var iLeft = (window.screen.availWidth-10-iWidth)/2;           //获得窗口的水平位置;
	  window.open(url,name,'height='+iHeight+',,innerHeight='+iHeight+',width='+iWidth+',innerWidth='+iWidth+',top='+iTop+',left='+iLeft+',toolbar=no,menubar=no,scrollbars=auto,resizeable=no,location=no,status=no');
  }
a2a_linkname = document.title;
a2a_linkurl = "";
</script>
		<?php echo $this->partial('partials/homeFooter.phtml')?>
</form>
	</div>
</div>