<div class="header">
	<h1 class="page-title">商品列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
<?php
if($this->action=='c'){
    echo "<li class=\"active\">欢迎推荐</li>[小提示：推荐的商品，在用户关注您的账号之后接收到的商品列表，建议不超过10个。]";
}else{
    echo "<li class=\"active\">商品列表</li>";
}
?>
	<?php if ($this->keywords){ ?>
	    <span class="divider">=></span><li class="active">当前搜索关键词：”<?php echo $this->keywords; ?>“</li>
	<?php }?>
	<li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
	<?php 
      if ($this->success)
    	{
    		echo "<div class=\"alert alert-success\">
    		<a class=\"close\" data-dismiss=\"alert\">×</a>
    		<strong>{$this->success->title}</strong>  {$this->success->message}</div>";
    	}
       if ($this->action=='c'){
           echo "<form name=\"commodityC\" method=\"post\"  >
        	     <div class=\"btn-toolbar\">
		         <button class=\"btn\">设为欢迎推荐</button>
			     <div class=\"btn-group\"></div></div>
	             ";
       }else 
       {
           ?>
       	<div class="btn-toolbar">
        <div class="search-well">
            <form class="form-inline" action="" method="post" >        
                <input class="input-xlarge" id="keywords"  name="keywords" type="text" value="<?php echo $this->keywords ;?>" style="margin-right: 5px;">
                <button class="btn" type="submit" onclick="return checkform();"><i class="icon-search"></i> 搜索</button>
            </form>
        </div>
            <?php if (($this->userData['commodityCount'] > $this->count || $this->userData['commodityCount']==0) && empty($this->action)){?>
			<a href="/commodity/create" class="btn btn-primary"><i class="icon-plus"></i> 添加商品</a>
			<?php }else{?>
			<a class="btn btn btn-danger"><i class="icon-remove"></i> 商品数量已满<?php echo $this->userData['commodityCount'];?>，不能再添加商品</a>
			<?php }?>
			<div class="btn-group"></div>
        </div>
       	<?php
       }
       ?>
		
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="3%">#</th>
						<th width="35%">二维码 / 缩略图 / 商品名称</th>
						<th width="12%">门店</th>
						<th width="8%">分类</th>
						<th width="10%">价格/折扣价</th>
						<th width="5%">库存</th>
						<th width="5%">售出</th>
						<th width="5%">点击</th>
						<th width="6%">上架</th>
						<th width="6%">推荐</th>
						<th style="width: 50px;">改 / 删</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
				    $i=0;
					foreach ($this->rows as $val) {
				?>
					<tr id="commodity_<?php echo $val['id'];?>">
						<td><?php 
						echo "<input type=\"checkbox\" name=\"id[]\" id=\"id\" value=\"{$val['id']}\"";
						if ($val['welcome']==1 && $this->action=='c') echo 'checked="checked"';
						echo " />";?></td>
						<td style="max-width:10%;"><div style="display: inline;" id="pics">
						<a href="http://api.kuaipai.cn/qr?chs=350x350&chl=<?php echo BASE_URL;?>/product?id=<?php echo $val['id'];?>" rel="[gall1]" title="微信扫一扫，在微信里预览！第<?php echo $i+1;?>张"><img src="http://api.kuaipai.cn/qr?chs=350x350&chl=<?php echo BASE_URL;?>/product?id=<?php echo $val['id'];?>" alt="微信扫一扫，在微信里预览！第<?php echo $i+1;?>张" width="30" height="20" /></a>
						<?php echo $val['thumb']?' <a href="'.$val['thumb'].'" rel="[gall1]" title="第'.($i+1).'张"><img src="'.$val['thumb'].'" alt="第'.($i+1).'张" width="30" height="20" /></a>':'  <font color="red">无图</font>'?></div>
						<?php 
						if($this->keywords){ 
                            echo str_replace($this->keywords,'<font color=red>'.$this->keywords.'</font>',$val['name']); 
                        }else{ 
                            echo $val['name']; 
                        }?>
                        </td>
						<td><?php echo isset($this->shop[$val['shop']])?$this->shop[$val['shop']]:'未知门店';?></td>
						<td><?php echo isset($this->type[$val['cateID']])?$this->type[$val['cateID']]:'未知分类';?></td>
						<td><?php echo $val['price'].'/'.$val['rebate'];?></td>
						<td><?php echo $val['repertory'];?></td>
						<td><?php echo $val['sold'];?></td>
						<td><?php echo $val['click'];?></td>
						<td><?php echo $val['added']==1?'已上架':'未上架';?></td>
						<td><?php echo $val['commend']==''?'未推荐':''?><?php echo $val['commend']==0?'未推荐':''?><?php echo $val['commend']==1?'普通推荐':''?><?php echo $val['commend']==2?'首页推荐':''?><?php echo $val['commend']==3?'幻灯推荐':''?></td>
						<td>
						<?php echo $this->bp->genActLink('commodity_edit',$this->bp->act_edit,'修改',array('id'=>$val['id']));?>
						 &nbsp;
						<?php echo $this->bp->genActLink('commodity_delete',$this->bp->act_del,'',array('del_id'=>$val['id']));?>
						</td>
					</tr>
					<?php 
					$i++;
					}
				}
				?>
				</tbody>
			</table>
		</div>
		<?php 
		echo $this->action=='c'?'</form>':'';
		echo $this->paginationcontrol($this->rows,'Sliding','pagination/pagination.phtml',array('ac'=>$this->action,'key'=>$this->keywords));
		?>
        <script type="text/javascript">			 
			 function triggerDel(del_id)
		     {
		   		$("#remove").click(function(){
					 
					  $.post('/commodity/delete?id='+del_id,{'id':del_id},function(data){
	                     if (data.isok==true)
	                     {
	                    	 $('#commodity_'+del_id).hide();
	                     }
	                 },'json');
					
				});		
		    }
		   </script>
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除商品</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>确定删除当前选定的商品？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="remove" data-dismiss="modal">确认</button>
			</div>
		</div>
		<?php 
		echo $this->partial('partials/homeFooter.phtml');
		?>
	</div>
</div>
<script type="text/javascript" charset="utf-8" src="/js/jquery-foxibox-0.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  $('#pics a').foxibox();
});
a2a_linkname = document.title;
a2a_linkurl = "";

function checkform(){
    var keywords = $('#keywords').val();
    if (keywords == 0 || keywords =='' ) {
        alert('请填写关键词！');
        return false;
    }
}
</script>