<div class="header">
	<h1 class="page-title">商品列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li class="active">被关注欢迎推荐</li>[小提示：推荐的商品，在用户关注您的账号之后接收到的商品列表，建议不超过10个。]
	<li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
	<?php 
	if ($this->success)
	{
		echo "<div class=\"alert alert-success\">
		<a class=\"close\" data-dismiss=\"alert\">×</a>
		<strong>{$this->success->title}</strong>  {$this->success->message}</div>";
	}
	?>
       <form name="commodityC" method="post"  >
        	     <div class="btn-toolbar">
		         <?php 
		          if (count($this->rows)) echo '<button class="btn">取消推荐</button>';
		         ?>
		         <a href="/commodity?action=c" class="btn btn-primary"><i class="icon-plus"></i> 添加推荐商品</a>
			     <div class="btn-group"></div></div>
		
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="3%">#</th>
						<th>商品名称</th>
						<th width="10%">门店</th>
						<th width="10%">分类</th>
						<th width="11%">价格/折扣价</th>
						<th width="5%">库存</th>
						<th width="5%">售出</th>
						<th width="8%">上架</th>
						<th width="8%">推荐</th>
						<th style="width: 50px;">改/删</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
				    $i=0;
					foreach ($this->rows as $val) {
				?>
					<tr id="commodity_<?php echo $val['id'];?>">
						<td><?php echo "<input type=\"checkbox\" name=\"id[]\" id=\"id\" value=\"{$val['id']}\"";?></td>
						<td><div style="display: inline;" id="pics">
						<?php echo $val['thumb']?' <a href="'.$val['thumb'].'" rel="[gall1]" title="第'.($i+1).'张"><img src="'.$val['thumb'].'" alt="第'.($i+1).'张" width="30" height="20" /></a>':'  <font color="red">无图</font>'?>
						<?php 
						if($this->keywords){ 
                            echo str_replace($this->keywords,'<font color=red>'.$this->keywords.'</font>',$val['name']); 
                        }else{ 
                            echo $val['name']; 
                        }?>
						</div>
                        </td>
                        <td><?php echo isset($this->shop[$val['shop']])?$this->shop[$val['shop']]:'未知门店';?></td>
						<td><?php echo isset($this->type[$val['cateID']])?$this->type[$val['cateID']]:'未知分类';?></td>
						<td><?php echo $val['price'].'/'.$val['rebate'];?></td>
						<td><?php echo $val['repertory'];?></td>
						<td><?php echo $val['sold'];?></td>
						<td><?php echo $val['added']==1?'已上架':'未上架';?></td>
						<td><?php echo $val['commend']==1?'已推荐':'未推荐'?></td>
						<td>
						<a href="/commodity/edit?id=<?php echo $val['id'];?>" title="修改"><i class="icon-pencil"></i></a>&nbsp;
						<a href="#myModal" role="button" data-toggle="modal" onclick="remove(<?php echo $val['id'];?>);" title="删除"><i class="icon-remove"></i></a>
						</td>
					</tr>
					<?php 
					$i++;
					}
					}
					?>
				</tbody>
			</table>
		</div>
		</form>
		<?php 
		echo $this->partial('partials/homeFooter.phtml');
		?>
	</div>
</div>
<script type="text/javascript" charset="utf-8" src="/js/jquery-foxibox-0.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  $('#pics a').foxibox();
});
a2a_linkname = document.title;
a2a_linkurl = "";
</script>