<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<meta charset="utf-8" />
	<title><?php echo $this->row['name'];?></title>
	<meta name="version" content="游太网络" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="description" content="<?php echo htmlspecialchars_decode(stripcslashes($this->row['weixin']));?>" />
	<meta name="keywords" content="<?php echo $this->row['name'];?>" /> 
	<link type="text/css" rel="stylesheet" href="/css/style.css" />
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/main.js"></script>
<style type="text/css">
button{width:100%;text-align:center;border-radius:3px;}
.button2{font-size:16px;padding:8px 0;border:1px solid #adadab;color:#000000;background-color: #e8e8e8;background-image:linear-gradient(to top, #dbdbdb, #f4f4f4);background-image:-webkit-gradient(linear, 0 100%, 0 0, from(#dbdbdb),to(#f4f4f4));box-shadow: 0 1px 1px rgba(0,0,0,0.45), inset 0 1px 1px #efefef; text-shadow: 0.5px 0.5px 1px #ffffff;}
.button2:active{background-color: #dedede;background-image: linear-gradient(to top, #cacaca, #e0e0e0);background-image:-webkit-gradient(linear, 0 100%, 0 0, from(#cacaca),to(#e0e0e0));}
#mess_share{margin:15px 10px;;}
#share_1{float:left;width:49%;}
#share_2{float:right;width:49%;}
#mess_share img{width:22px;height:22px;}
.option_green,.option_gray{float:left;height:10px;margin:8px 0;overflow:hidden;}
.option_green{background-color:#00b93c;}
.option_gray{background-color:#cccccc;}
.option_title,.option_info{padding:5px 0;}
.option_title{float:left;}
.option_info,.option_vote{float:right;margin-left:5px;color:#666666;}
.option_vote img{width:25px;height:25px;}
</style>
</head>
<body>
	<?php echo $this->partial ( 'partials/header.phtml');?>
<!--主体-->
<div class="main">
	<div class="banner" id="banner">
		   <div class="index-focus" id="indexfocus">
                <ul>
		<?php
		$images = $this->row['images'];
		//$images = unserialize($this->row['images']);
		if ($images && is_array($images))
		{
			$i=0;
			foreach ($images as $val) {
                //if ($i) continue;
				echo "<li><span class=\"car-pic\"><img src=\"".$val->path."\"></span></li>\n";
				$i++;
			}
		}else 
		{
	       echo "<li><span class=\"car-pic\"><img src=\"".$this->row['thumb']."\"></span></li>\n";
		}
		?>
				</ul>
           </div>
		<h1 class="p_title"><?php echo $this->row['name'];?></h1>
	</div>
	<div class="index-focus-num" id="index-focus-num">
            <ul>
		<?php
		$images = $this->row['images'];
		//$images = unserialize($this->row['images']);
		if ($images && is_array($images))
		{
			$i=0;
			foreach ($images as $val) {
				$imgSrc = "<img src='".$val->path."' />";
                if(!$i) 
                {
                    echo "<li class=\"current\"></li>";
                }else{
                    echo "<li></li>";
				}
				$i++;
			}
		}else{
            echo "<li class=\"current\"></li>";
			//echo "<li class=\"current\"></li>";
        }
		?>
            </ul>
	</div>
	<div class="p_buy clearfix" id="p_buy">
		<span class="p_price">
			￥<?php echo $this->row['rebate'];?>
			<font class="p_price_pass">￥<?php echo $this->row['price'];?></font>
		</span>

		<!--检查库存 /product/indent?id=< ? php echo $this->row['id']; ? > javascript:add_cart(< ?php echo $this->row['id'];? >) -->
		   <a href="javascript:void(0);" class="p_btn_buy">
			<span class="ts1">抢购</span>
		   </a>
			</div>
			
			
			<div class="product_info single_con" id="product_info">              
            
	       <form id="fstyle" method="post" onsubmit="return sub()">
		   	  <?php if($this->specList):?>
			  	<?php echo $this->specList;?>
			  <?php endif;?>
	        <p>
		    	<span class="product_tit">数量:</span>
	            <span class="reduction_n" onclick="buycountFu('-')"></span>
	            <span class=""> <input type="text" value="1" name="num" class="number_info" onchange="buycountFu(this.value)" id="buycount" maxlength="3"></span>
	            <span class="plus" onclick="buycountFu('+')"></span> 
	        </p>   
	       </form>
	  
 </div>
 <div id="alert_car" style="background:#FFF; padding-bottom:10px; border-bottom:#D5D5D5 solid 1px;">
             <p class="clearfix claxxx"> <span class="ercen fle">
  <input type="submit" value="立即购买" onclick="add_cart(<?php echo $this->row['id'];?>,1);" class="bt_green" /> </span>
 <span class="ercen fri"> <input type="button" onclick="add_cart(<?php echo $this->row['id'];?>,0);" value="加入购物车" class="bt_pink" /></span> </p>
             
           </div>
	<div class="p_tn clearfix">
		<p>
			<!--<span class="p_time">大于3天</span>-->
			<span class="p_num"><?php echo $this->row['sold']?$this->row['sold']:'0';?>人已购买</span>
		</p>
		<!-- <p class="p_show_com clearfix">
			<a href="/product/comments?id=<?php echo $this->row['id'];?>">
				<font>商品评论（<?php echo $this->row['comment'];?>）</font>
				<span class="p_comment clearfix">
					评分
					<font class="p_com_num">8.0</font>
					<span class="p_com_b">
						<span class="p_com_t" style="width: 80%;"></span>
					</span>
				</span>
				<span class="gt"></span>
			</a>
		</p> -->
	</div>
	<div class="p_mod p_short_desc">
		<h2 class="p_mod_title">商品描述</h2>
		<div class="p_con">
			<?php echo htmlspecialchars_decode(stripcslashes($this->row['weixin']));?>
		</div>
		   <a href="/product/moreinfo?id=<?php echo $this->row['id'];?>" class="p_to_desc" style="color:red;font-weight:bold">查看商品图文详情>>><span class="gt"></span></a>
	</div>
	<div class="p_mod p_seller_info">
		<a href="/stores?id=<?php echo $this->row['shop'];?>">门店信息 <font>共<?php echo $this->countshop;?>家分店</font><span class="gt"></span></a>
	</div>
	<!--div class="p_mod p_tip">
		<h2 class="p_mod_title">特别提醒</h2>
		<div class="p_con">
			<p>
				产品咨询：商家电话：15989377520 产品咨询：商家电话：15989377520产品咨询：商家电话：15989377520 产品咨询：商家电话：15989377520 产品咨询
			</p>
		</div>
	</div-->
   <?php 
   if ($this->rows)
   {
       foreach ($this->rows as $val) {
   ?>
	<section class="i_list">
		<ul>
			<li>
				<a href="/product?id=<?php echo $val['id'];?>">
					<img src="<?php echo $val['thumb'];?>" />
					<h3><?php echo $val['name'];?></h3>
					<p class="tui_price ts2">
						<strong>￥<?php echo $val['rebate'];?></strong>
						<del>￥<?php echo $val['price'];?></del>
						<span><cite><?php echo $val['sold']?$val['sold']:'0';?></cite> 人购买
						</span>
					</p>
					<?php if($val['sales']>'5'){ ?><div class="hot"><strong>热卖</strong></div><?php } ?>
				</a>
			</li>
		</ul>
	</section>
	<?php
	 } 
   }
	?>
	    <div class="p_mod p_seller_info p_tips ts2"><a href="/product/list" style="color:red;font-weight:bold">更多精彩抢购>>><span class="gt"></span></a></div>
	<!--<div class="p_mod p_tips clearfix">
		<font class="p_ren">官方认证商铺</font>
		<font class="p_tui">支持七天退换</font>
	</div>-->
</div>

<script type="text/javascript">
window.onload = function(){
	//价格与抢购按钮浮动
	var f_obj = document.getElementById('p_buy');
	var f_y = f_obj.offsetTop;
	var f_class = f_obj.className;
	document.onscroll = function(){
		if(document.body.scrollTop>f_y){
			f_obj.className += " fixed_t";
		}else{
			f_obj.className = f_class;
		}
	}
	img_size();
}
</script>
    <script src="/js/SlideTurnPage.js" type="text/javascript"></script>
    <script>
        var slider = new Swipe(document.getElementById('indexfocus'), {
            callback: function (e, pos) {
                var i = bullets.length;
                while (i--) {
                    bullets[i].className = ' ';
                }
                bullets[pos].className = 'current';
            },
            auto: 3000,
            speed: 400
        });
        bullets = document.getElementById('index-focus-num').getElementsByTagName('li');
    </script>
    <script type="text/javascript">
	
	$(document).ready(function(){
		$(".spec_item").click(function(){
			$(this).addClass("current1");
			$(this).siblings().removeClass("current1");
		});	
	});
	
	
    /*数量加减*/

    function buycountFu(n, t, i) {
        t = t || "";
        var u = $("#buycount" + t),
        r = parseInt(u.val(), 10);
        if (n == "+") {
            if (r >= 999) return;
            u.val(++r)
        } else n == "-" && r > 1 ? u.val(--r) : !isNaN(n) && $.trim(n) != "" && parseInt(n, 10) > 0 && parseInt(n, 10) <= 999 ? u.val(n) : u.val(1);
        r <= 1 ? visibleBtn("reduction_n.png", "plus.png") : r >= 999 ? visibleBtn("reduction.png", "plus_n.png") : visibleBtn("reduction.png", "plus.png"),
        i && i.call(window, t)
    }
    function visibleBtn(n, t) {
        $(".reduction_n:visible").css("background-image", "url(/images/" + n + ")"),
        $(".plus:visible").css("background-image", "url(/images/" + t + ")")
    }


    /*选择框*/

    /*function showSize(n) {
        $("#productsizes>.current1").removeClass("current1"),
        $("#size_" + n).addClass("current1"),
        $("#clotheCode").val(n)
    }*/


   /* function showSi(n) {
        $("#productsizes1>.current1").removeClass("current1"),
        $("#sie_" + n).addClass("current1"),
        $("#clotheCode").val(n)
    }*/
    </script>
<?php echo $this->partial ( 'partials/footer.phtml');?>
<?php echo $this->partial('partials/stats.phtml');?>
</body>
</html>