<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo $this->news_info['title']; ?></title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <meta content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="yes" name="apple-mobile-web-app-capable" />
    <meta content="black" name="apple-mobile-web-app-status-bar-style" />
    <meta content="telephone=no" name="format-detection" />
    <meta content="<?php echo $this->news_info['title']; ?>" name="keywords" />
    <meta content="<?php echo $this->news_info['title']; ?>" name="description" />
    <link href="/css/plug/strap/activity_style.css" media="all" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="/sitetem/common/css/commonjia.css" media="all" />
<link rel="stylesheet" type="text/css" href="/wz/css/font-awesome.css" media="all" />
  	<script>
    window.addEventListener("DOMContentLoaded", function(){
        btn = document.getElementById("plug-btn");
        btn.onclick = function(){
            var divs = document.getElementById("plug-phone").querySelectorAll("div");
            var className = className=this.checked?"on":"";
            for(i = 0;i<divs.length; i++){
                divs[i].className = className;
            }
            document.getElementById("plug-wrap").style.display = "on" == className? "block":"none";
        }
    }, false);
    </script>
</head>
<body class="activity-scratch-card-winning">
    <div id="loading" class="red">
    加载中...
    </div>
    <div class="main" id="container" style="display:none">
        <div class="cover">
            <img src="/images/plug/strap/activity-scratch-card-bannerbg.png" />
            <div id="prize"></div>
            <div id="scratchpad"></div>
        </div>
        <div class="content">
            <div class="boxcontent boxwhite" id="zjl" style="display: none">
                <div class="box">
                    <div class="title-red">
                        <span>恭喜你中奖了</span>
                    </div>
                    <div class="Detail">
                        <p>你中了：<span class="red" id="pzname"></span></p>
                        <p>兑奖SN码：<span class="red" id="sncode"></span></p>
                        <p><input class="px" id="tel" name="" placeholder="用户请输入您的手机号" type="text" value="" /></p>
                        <p></p>
                        <p><input class="pxbtn" id="save_btn" name="提 交" type="button" value="用户提交" /></p>
                        <input type="hidden"  id="prize_id" />
                        <input type="hidden"  id="activity_id" />
                    </div>
                </div>
            </div>
            <div class="boxcontent boxwhite">
                <div class="box">
                    <div class="title-red">
                        <span>奖项设置：</span>
                    </div>
                    <div class="Detail">
                        <?php
                            $prizes = array();
                            if($this->disk_info){
                                foreach($this->disk_info as $item){
                                    if($item['type'] > 0){
                                        array_push($prizes,$item);
                                    }
                                }
                            }
                            
                            function sort_prize($a,$b){
                                return ($a['type'] <=  $b['type'] ? -1:1);
                            }
                            
                            usort($prizes,'sort_prize');
                            for($i=0;$i<count($prizes);$i++){
                                echo "<p>" . $prizes[$i]['name'] . "：" . $prizes[$i]['prize'] . " 奖品数量：" . $prizes[$i]['count'] . "</p>\n";
                            }
                        ?>
                    </div>
                </div>
            </div>
            <div class="boxcontent boxwhite">
                <div class="box">
                    <div class="title-red">
                        活动说明：
                    </div>
                    <div class="Detail">
                        <p class="red">本次活动您还可以刮<span id="left_chance"><?php echo json_encode($this->play_count); ?>次,机会如果没用完重新进入本页面可以再刮!</span></p>
                        <p>
                        <?php
                            if($this->news_info){
                                echo $this->news_info['description'];
                            }
                        ?>
                        </p>
                    </div>
                </div>
            </div>
            
             <div class="boxcontent boxwhite">
                <div class="box">
                    <div class="title-red">
                        我的中奖记录：
                    </div>
                    <div class="Detail">
                        <div id="won_prizes">
                            <?php
                            
                            if($this->won_prizes){
                                for($i=0;$i<count($this->won_prizes);$i++){
                                    echo '<p>奖品：'.$this->won_prizes[$i]['name'].'</p><p style="padding-left:10px;">奖码：<span class="red">'.$this->won_prizes[$i]['sn'].'</span></p><p style="padding-left:10px;">中奖时间：'.$this->won_prizes[$i]['prize_time'].'</p>';
                                }
                            }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div style="clear: both;"></div>
        <footer style="text-align:center; color:#ffd800;margin-right:20px">
        <a style=" text-decoration: none; color: #AAFF00; font-size:12px;font-family: '宋体'; font-weight: lighter;" href="http://www.veigou.com/" target="_blank">游太网络技术支持</a>
    </footer>
    </div>
        <?php echo $this->partial('partials/bottomjia.phtml');?>
</body>
</html>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/nice_alert.js"></script>
<script src="/js/plug/strap/wScratchPad.js"></script>
<script type="text/javascript">
    var ERR_OK=0;
    var ERR_ILLEGAL_ID=1;
    var ERR_MISS_ID=2;
    var ERR_NOT_OPEN=3;
    var ERR_CLOSED=4;
    var ERR_NOT_LOGIN=5;
    var g_err_info = <?php echo json_encode($this->err_info); ?>;
    var g_err_code = <?php echo json_encode($this->err_code); ?>;
    var g_play_count = <?php echo json_encode($this->play_count); ?>;
    var g_pride_result = null;
    var num = 0;
    var goon = true;
    
    function init_data(){
        if(g_err_info){
            if(g_err_code == ERR_NOT_LOGIN){
                nice_alert(g_err_info,function(){onLogin();});
            }else{
                nice_alert(g_err_info,function(){onRedirectHome();});
            }
            return false;
        }
        
        $.getJSON(window.location.href.replace(/(\/scratch)([^\w])/,'/prize$2'),function(result){
            if(result.code !='ok'){
                $('#loading').html(result.msg);
                return;
            }else{
                g_pride_result = result;
                $('#prize').html(result.data.prize);
                $('#pzname').html(result.data.prize);
                $('#sncode').html(result.data.sn);
                $('#left_chance').html(result.data.play_count);
                $('#prize_id').val(result.data.id);
                $('#activity_id').val(result.data.activity_id);
                $('#loading').hide();
                $('#container').show();
            }
        });
        return true;
    }
    
    $(function () {
        if(!init_data()){
            return;
        }
        var useragent = window.navigator.userAgent.toLowerCase();
        $("#scratchpad").wScratchPad({
            width: 150,
            height: 40,
            color: "#a9a9a7",
            scratchMove: function (e,percent) {
                num++;
                if (g_pride_result.data.type>0 && num > 5 && goon) {
                    goon = false; 
                    $("#zjl").slideToggle(500);
                }
                if (useragent.indexOf("android 4") > 0) {
                    if ($("#scratchpad").css("color").indexOf("51") > 0) {
                        $("#scratchpad").css("color", "rgb(50,50,50)");
                    } else if ($("#scratchpad").css("color").indexOf("50") > 0) {
                        $("#scratchpad").css("color", "rgb(51,51,51)");
                    }
                }
            }
        });
    });
    
    $("#save_btn").click(function(){
        var phone_reg = /^1[3|4|5|8][0-9]\d{4,8}$/;
        if(!phone_reg.test($.trim($('#tel').val()))){
            nice_alert('请填写正确的手机号!');
            return;
        }
        var submit_url = "/s/activity/savephone?id=" + $.trim($('#activity_id').val());
        var post_data = {
            'prize_id' : $.trim($('#prize_id').val()),
            'phone' : $.trim($('#tel').val())
        };
        
        $.ajax({
            type: 'POST', 
            url: submit_url, 
            dataType: 'json',
            data:post_data,
            cache: false, 
            error: function(){ 
                nice_alert('出错了！'); 
                return false; 
            }, 
            success:function(json){ 
                if(json.code !='ok'){
                    nice_alert(json.msg);
                }else{
                    //nice_alert("已登记手机号码！");
                    $('#zjl').hide();
                }
            } 
        });  
    }); 
    
    function onLogin(){
        document.cookie = "_refer=" + window.location.href + ";path=/";
        window.location.href="/user/login";
    }

    function onRedirectHome(){
        window.location.href="/";
    }
</script>
        <?php echo $this->partial('partials/stats.phtml');?>
