<section>
    <div class="plug-div">
        <div id="plug-phone" class="plug-phone">
            <input id="plug-btn" type="checkbox" name="" value="" class="plug-menu" style="background-color:#B91D1D;"/>
           <div class="" style="background-color:#B91D1D;"><a href="/index/artlist" class="icon-list-ul"></a></div>
           <div class="" style="background-color:#B91D1D;"><a href="/product/list" class="icon-shopping-cart"></a></div>
           <div class="" style="background-color:#B91D1D;"><a href="/index/bltlist" class="icon-bullhorn"></a></div>
           <div class="" style="background-color:#B91D1D;"><a href="/" class="icon-home"></a></div>
         </div>
    </div>
</section>  