<link rel="stylesheet" href="/lib/uploadify/uploadify.css">
<div class="control-group" id="group-fileField">
  <label class="control-label" for="upload">上传图片<br><span style="font-size:8px;">[小贴士：1.请不要上传过大的图片，分辨率640PX：320px<br>2.本功能是多图上传，请将要传的图片全部选中上传<br>3.上传建议不超过5张，更多图文请在“图文详情”里描述]</span></label>
   <div id="pics">                
    </div>
  <div class="controls">
    <input type="file" name="upload" id="upload" />
    <span id="uploads"></span> <span class="help-inline" id="help-sold"></span> </div>
</div>

<script type="text/javascript">
	<?php $timestamp = time();?>
    $(function() {
       $('#upload').uploadify({
       'buttonText' : '选择文件',
       'fileSizeLimit' : '2048KB',
		'fileTypeDesc' : '选择图片',
       'fileTypeExts' : '*.gif; *.jpg; *.png',
       'fileObjName' : 'fileField',
       'method'   : 'post',
		'formData'     : {
			'timestamp' : '<?php echo $timestamp;?>',
			'token'     : '<?php echo md5("unique_salt" . $timestamp);?>',
				'act'		: 'add',
				'_identify'	: '<?php echo $this->uploadParams["_identify"]?>',
				'module_id'	: '<?php echo $this->uploadParams["module_id"]?>'
		},
		'swf'      : '/lib/uploadify/uploadify.swf',
		'uploader' : '/commodity/ajaxUpload',
		'onUploadSuccess':function(file,data,response){
                if (response && data!="error")
                {
                        $('#uploads').append('<input type="hidden" name="images[]" value="'+data+'">');
                        $('#pics').append('<a><img src="'+data+'" width="60" height="30" /></a>');
                }
		}
	 });
  });
  
  $(document).ready(function(){
	  $('#pics a').foxibox();
  });
</script>
<script type="text/javascript" charset="utf-8" src="/js/jquery-foxibox-0.2.min.js"></script>
<script src="/lib/uploadify/jquery.uploadify.min.js"></script>
  