<div class="header">
	<h1 class="page-title">编辑订单</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/indent">订单列表</a> <span class="divider">/</span></li>
	<li class="active">编辑订单</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
<form id="tab" name="editIndent" method="post" action="?id=<?php echo $this->row['serialnumber'];?>">
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<div class="btn-group"></div>
		</div>
		<div class="well">
				<ul class="nav nav-tabs">
					<li><a href="/indent/view?id=<?php echo $this->row['serialnumber'];?>">订单详情</a></li>					
					<li class="active"><a>商家发货</a></li>
				</ul>
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane active in" id="home">
				         <div class="control-group" id="group-transport">
							<label class="control-label" for="transport">物流方式</label>
							    <input type="radio" name="transport" id="transport_1" value="1" <?php echo $this->row['transport']==1 ?'checked="checked"':''?>/> 平邮
							    <input type="radio" name="transport" id="transport_2" value="2" <?php 
							    if ($this->row['transport']==2 || empty($this->row['transport']))
									{
										echo 'checked="checked"';
									}
							    ?>/> 快递
							    <input type="radio" name="transport" id="transport_3" value="4" <?php echo $this->row['transport']==4 ?'checked="checked"':''?>/> 不需要物流
                                <span class="help-inline" id="help-transport"></span>
							</div>
						</div>
						
				         <div class="control-group" id="group-express" <?php
				         if ($this->row['transport'] != 2 && $this->row['transport'])
				         {
				         	echo 'style="display: none;"';
				         }
				         ?> >
							<label class="control-label" for="express">物流公司</label>
							<div class="controls">
								<select name="express" id="express">
								<option value="0">请 选 择</option>
								<?php 
								foreach ($this->express as $val) {
									echo "<option value=\"{$val}\"";
									if ($this->row['express']==$val) echo 'selected="true"';
									echo ">{$val}</option>\n";
								}
								?>
								</select>
                                <span class="help-inline" id="help-express"></span>
							</div>
						</div>
						 <div class="control-group" id="group-waybill" <?php echo $this->row['transport']==4?'style="display: none;"':''?>>
							<label class="control-label" for="waybill">运单号</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['waybill'];?>" id="waybill" name="waybill" class="input-xlarge">
                                <span class="help-inline" id="help-waybill"></span>
							</div>
						</div>
                        <div class="control-group" id="group-status">
							<label class="control-label" for="status">状态</label>
							<div class="controls">
								<select name="status" id="status">
								<?php 
								foreach ($this->status as $key=>$val) {
                                    if($key==2 || $key==3 || $key==5) continue;
									echo "<option value=\"{$key}\"";
									if ($this->row['status']==$key) echo 'selected="true"';
									echo ">{$val}</option>\n";
								}
								?>
								</select>
                                <span class="help-inline" id="help-display"></span>
							</div>
						</div>
						<div class="control-group" id="group-content">
							<label class="control-label" for="content">备注</label>
							<div class="controls">
								<textarea rows="5" class="span5" name="content"><?php echo htmlspecialchars_decode(stripcslashes($this->row['content']));?></textarea>
                                <span class="help-inline" id="help-content"></span>
							</div>
						</div>
						
				</div>
			</div>

		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>
<script type="text/javascript">
$(function(){
	$('#transport_1').click(function(){
		$('#group-express').hide();
		$('#group-waybill').show();
		});
	$('#transport_2').click(function(){
		$('#group-express').show();
		$('#group-waybill').show();
		});
	$('#transport_3').click(function(){
		$('#group-express').hide();
		$('#group-waybill').hide();
		});
});
</script>