<div class="header">
  <h1 class="page-title">添加消息</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/home">首页</a> <span class="divider">/</span></li>
  <li><a href="/News">消息</a> <span class="divider">/</span></li>
  <li class="active">添加消息</li>
</ul>
<div class="container-fluid">
  <div class="row-fluid">
    <form id="tab" name="autoreplyCreate" method="post" action=""  onsubmit="return clickForm();" enctype="multipart/form-data">
      <div class="btn-toolbar">
        <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
        <div class="btn-group"></div>
      </div>
      <div class="well">
            <div class="control-group" id="group-url">
              <label class="control-label" for="url">标题</label>
              <div class="controls">
                <input type="text" value="" name="url" id="url" class="span3">
                <span class="help-inline" id="help-url"></span> </div>
            </div>
            <div class="control-group" id="group-thumbnail">
              <label class="control-label" for="thumbnail">缩略图</label>
              <div class="controls">
                <input type="file" value="" name="thumbnail">
                <span class="help-inline" id="help-thumbnail"></span> </div>
            </div>
            <div class="control-group" id="group-description">
              <label class="control-label" for="description">描述</label>
              <div class="controls">
                <textarea type="text" value="" name="description" id="description" class="span3"></textarea>
                <span class="help-inline" id="help-description"></span> </div>
            </div>
          <div class="control-group" id="group-url">
              <label class="control-label" for="url">链接地址</label>
              <div class="controls">
                <input type="text" value="" name="url" id="url" class="span3">
                <span class="help-inline" id="help-url"></span> </div>
            </div>
      <script type="text/javascript">
		<?php $timestamp = time();?>
           $(function() {
           $('#upload').uploadify({
           'buttonText' : '缩略图文件',
           'fileSizeLimit' : '2048KB',
           'fileTypeDesc' : 'Image Files',
           'fileTypeExts' : '*.gif; *.jpg; *.png',
           'fileObjName' : 'thumbnail',
           'method'   : 'post',
                				'formData'     : {
                					'timestamp' : '<?php echo $timestamp;?>',
                					'token'     : '<?php echo md5('unique_salt' . $timestamp);?>',
                				},
                				'swf'      : '/lib/uploadify/uploadify.swf',
                				'uploader' : '/uploadify.php',
                				'onUploadSuccess':function(file,data,response){
                                    if (response && data!="error")
                                        {
                                            $('#uploads').append('<input type="hidden" name="images[]" value="'+data+'">');
                                        }
                    				}
                			});
         });
     </script> 
      <?php echo $this->partial('partials/homeFooter.phtml')?>
    </form>
  </div>
</div>
<script src="/ueditor/ueditor.all.min.js"></script>
<script src="/ueditor/ueditor.config.js"></script>