<!DOCTYPE html> 
<html> <head> 
    <title><?php if(isset($this->navInfo['scLabel']) && !empty($this->navInfo['scLabel'])){ echo $this->navInfo['scLabel']; }else{ echo $this->_artlist; }?> - <?php echo $this->_siteInfo['realname'];?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0;" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="description" content="<?php echo $this->_siteInfo['realname'];?>">
    <meta name="keywords" content="<?php echo $this->_siteInfo['realname'];?>">
    <link rel="stylesheet" type="text/css" href="/sitetem/default/css/party.css" />
    <link type="text/css" rel="stylesheet" href="/sitetem/default/css/style.css" />
 	<link rel="stylesheet"type="text/css" href="/sitetem/default/css/ttt.css">
    <link rel="stylesheet" type="text/css" href="/sitetem/common/css/commonjia.css" media="all" />
    <link rel="stylesheet" type="text/css" href="/wz/css/font-awesome.css" media="all" />
  	<script type="text/javascript" src="/sitetem/js/main.js"></script>
  	<script>
    window.addEventListener("DOMContentLoaded", function(){
        btn = document.getElementById("plug-btn");
        btn.onclick = function(){
            var divs = document.getElementById("plug-phone").querySelectorAll("div");
            var className = className=this.checked?"on":"";
            for(i = 0;i<divs.length; i++){
                divs[i].className = className;
            }
            document.getElementById("plug-wrap").style.display = "on" == className? "block":"none";
        }
    }, false);
    </script>
    </head>
    <body>
    	<section id="page-wrapper">
        	<section id="menu-wrapper">
            <?php echo $this->partial('partials/left_menu.phtml');?>
            </section> <!-- #menu-wrapper -->        
        	<section id="content-wrapper" style=" min-height:461px;">
                <section id="header">
                    <div id="header-left">
                        <a href="#" id="a-menu"><img src="/sitetem/default/images/menu.png" alt="menu" /></a>
                    </div>
                   <div id="header-title"><h1><a class="ui-title" id="popmenu">
                   <?php
                       if(isset($this->navInfo['scLabel']) && !empty($this->navInfo['scLabel'])){
                           echo $this->navInfo['scLabel'];
                       }else{
                           echo $this->_artlist;
                       }
                   ?> ▼</a></h1></div>                  
                     <header>
                       <ul class="navigationa">
     					 <li class="nav_searcha"><a href="#"></a></li>
    					</ul>
                      </header>
                        
                    <div id="overlay"></div>
                       <div id="win">
                    <ul class="dropdown">
                    <?php if($this->ssbclass):?>
                      <?php foreach($this->ssbclass as $sk=>$sv):?>
                          <li><a href="/index/artlist?sc=<?php echo $sv['id']?>"><span><?php echo $sv['name']?></span></a></li>
                      <?php endforeach;?>
                    <?php endif;?> 
                     <div class="clr"></div>
                    </ul>
          </div>    
                </section>
                <div class="gz_1">
             <div id="search">
      <form class="search" action="" method="GET">
        <fieldset class=" ">
        <input type="text" placeholder="请输入你要搜索的关键词" class="text " name="keyword">
        <input type="submit" value="search" class="submit">
        </fieldset>
      </form>
    </div>
    <div style=" color:#666; padding:3px 0 3px 20px;background: url(/sitetem/default/images/list_home.png) left 10px no-repeat;height:20px; margin:10px;">
		<a href="/">首页</a>》<a href="/index/artlist"><?php echo $this->_artlist;?></a><?php echo $this->navInfo['navStr'];?></div>
      <ul class="g_1">
	  	<?php 
			if(isset($this->artlist)):
				foreach($this->artlist as $row):
		?>
         <li class="g_a">
         <div class="g_v">
         <a href="/index/artdetail?art_id=<?php echo $row->art_id;?>"><img src="<?php echo $row->thumb?>" alt="" width="80" height="60"/></a>
         <em class="g_1_1"><?php if(isset($this->types[$row->subclassid])){echo "<a href='/index/artlist?sc=".$row->subclassid."' style='color:#fff'>".$this->types[$row->subclassid]."</a>";}?></em>	
         </div>	
			<div class="g_2">
			<a href="/index/artdetail?art_id=<?php echo $row->art_id;?>" class="list_title" target="_blank"><div><?php echo $row->art_title;?></div></a>
				<div class="g_3"><?php echo $row->username;?></div>
				<span style="float:left;">发表于<em><?php echo date('Y-m-d H:i:s',$row->created_time);?></em></span>
			</div>
		</li>
		<?php
				endforeach; 
			endif;
		?>
     </ul>
      </div>
      <section id="Page_wrapper">
          <div id="pNavDemo" class="c-pnav-con">
                <section class="c-p-sec">
                <?php if(isset($this->pager)) {echo $this->pager;}?>
                </section>
         </div>
    </section> 
        <div id="duty"><div id="ft" style="margin:10px 10px 0 10px"><p class="wrapper copyright">由&#160;[唯购]游太网络&#160;提供技术支持</p></div></div>
            </section> <!-- #content-wrapper -->
    	</section> <!-- #page-wrapper -->
        <?php echo $this->partial('partials/bottomjia.phtml');?>
        <script src="/sitetem/js/jquery.min.js"></script>
		<script src="/sitetem/js/jquery-ui-1.8.16.custom.min.js"></script>
        <script src="/sitetem/js/site.js"></script>
        <script language="javascript">
        <!--
        function MM_jumpMenu(targ,selObj,restore){ //v3.0
          eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
          if (restore) selObj.selectedIndex=0;
        }
        //-->
        </script>       
        <?php echo $this->partial('partials/stats.phtml');?> 
    </body>
</html>