<?php 
use module\Application\src\Model\Tool;
use Admin\Model\Role;
$children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>唯购管理系统</title>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link rel="stylesheet" type="text/css" href="/lib/bootstrap/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="/css/theme.css">
<link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.css">
<?php 
if (isset($child->asset))
{
	if (isset($child->asset['css']) && is_array($child->asset['css']))
	{
		foreach ($child->asset['css'] as $val) {
			echo "<link rel=\"stylesheet\" href=\"{$val}\">".PHP_EOL;
		}
	    
	}
}
?>
<script src="/lib/jquery-1.7.2.min.js" type="text/javascript"></script>
<script src="/lib/jquery.cookie.js" type="text/javascript"></script>
<style type="text/css">
#line-chart {
	height: 300px;
	width: 800px;
	margin: 0px auto;
	margin-top: 1em;
}
.brand {
	font-family: georgia, serif;
}
.brand .first {
	color: #ccc;
	font-style: italic;
}
.brand .second {
	color: #fff;
	font-weight: bold;
}
/*
thead tr,tbody tr{
	white-space: nowrap;
	max-width:20%;
}*/
tr.dbl td{
	background:#FAFAFA;
}
tr.over td{
	background:#C5E4F3;
}
</style>
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="/lib/html5.js"></script>
    <![endif]-->
</head>

<!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
<!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
<!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
<!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<body class="">
<!--<![endif]-->
<?php 
if (isset($child->user))
{
?>
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav pull-right">
		<?php if($child->user->power ==3):?>
			<li><a href="/users/clearcache" class="hidden-phone visible-tablet visible-desktop" role="button">清除系统缓存</a></li>
		<?php endif;?>
	  
      <li><a href="/users/edit" class="hidden-phone visible-tablet visible-desktop" role="button">账号设置</a></li>
      <li id="fat-menu" class="dropdown"><a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> 
      <i class="icon-user"></i>
      <?php echo $child->user->realname;?><i class="icon-caret-down"></i> </a>
        <ul class="dropdown-menu">
          <li><a tabindex="-1" href="/users/edit">我的账号</a></li>
          <li class="divider"></li>
          <li><a tabindex="-1" href="/logout">退出系统</a></li>
        </ul>
      </li>
    </ul>
    <a class="brand" href="/home"><!-- <span class="first">微信</span>  --><span	 class="second">
    <?php 
    if ($child->user->power==1) echo '唯购分店管理平台<span style="font-size:8px;color:#999;">v2.96</span>';
    if ($child->user->power==2) echo '唯购总管理平台<span style="font-size:8px;color:#999;">v2.96</span>';
    if ($child->user->power==3) echo '唯购平台<span style="font-size:8px;color:#999;">v2.96</span>';
    ?>
           
    </span></a> </div>
</div>
<div class="sidebar-nav">
	<?php
		$sm = $this->getHelperPluginManager()->getServiceLocator();
		$_adapter = $sm->get('Zend\Db\Adapter\Adapter');
		$db=new Role($_adapter);
		$menu = Tool::genRoleMenu($db->getAccessTree(0,$child->user->roleid,$child->user->domain));
		echo $menu;
	?>
</div>
<?php 
}
?>
<div class="content"><?php echo $this->content;?> </div>
<script src="/lib/bootstrap/js/bootstrap.js"></script> 
<script src="/js/scrm-core.js"></script> 
<script src="/lib/jquery-validate.min.js"></script>
<script src="/js/admin.js" type="text/javascript"></script> 
<?php 
if (isset($child->asset))
{
    if (isset($child->asset['js']) && is_array($child->asset['js']))
    {
        foreach ($child->asset['js'] as $val) {
        	echo "<script src=\"{$val}\"></script>".PHP_EOL;
        }
    }
}
?>
<script type="text/javascript">
function show_help(){
    document.getElementById("helpcontroller").innerHTML='<div class=\"alert\" style=\"margin-top:10px;\"><?php print(Tool::getCache('acl_help'));?></div>';
}
</script>
<script type="text/javascript">
        $("[rel=tooltip]").tooltip();
        $(function() {
            $('.demo-cancel-click').click(function(){return false;});
        });
    </script>
</body>
</html>