<style type="text/css">
	.editor{
		width:900px;
		height: 450px;
	}
	
</style>
<div class="header">
	<h1 class="page-title">添加活动</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/home"><?php echo $this->bp->genActLink('party_index',$this->bp->act_link,'活动报名');?></a> <span class="divider">/</span></li>
	<li class="active">添加活动</li>
	<li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
<form id="tab" name="createUser" method="post" action="" onsubmit="return checkArt();" enctype="multipart/form-data">
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<div class="btn-group"></div>
		</div>
		<div class="well">
			
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane active in" id="home">
						<div class="control-group" id="group-art_title">
							<label class="control-label" for="party_title">标题</label>
							<div class="controls">
								<input type="text" value="" id="party_title" name="party_title" class="span5">
                                <span class="help-inline" id="help-party_title"></span>
							</div>
						</div>
						
						<div class="control-group" id="group-password">
							<label class="control-label" for="password">独立查看密码</label>
							<div class="controls">
								<input type="text" value="" id="password" name="password" class="span3">
                                <span class="help-inline" id="help-password"></span>
							</div>
						</div>
						
						<div class="control-group" id="group-author">
							<label class="control-label" for="author">作者</label>
							<div class="controls">
								<input type="text" value="" id="author" name="author" class="span2">
                                <span class="help-inline" id="help-author"></span>
							</div>
						</div>
						
						<div class="control-group" id="group-joinname">
							<label class="control-label" for="joinname">报名名称自定义</label>
							<div class="controls">
								<input type="text" value="我要报名" id="joinname" name="joinname" class="span2">
                                <span class="help-inline" id="help-joinname"></span>
							</div>
						</div>	
						
						<div class="control-group" id="group-mp">
							<label class="control-label" for="mp">公众号<span style="font-size:8px;">[小贴士：如果为用户安卓系统，将提示关注公众号]</span></label>
							<div class="controls">
								<input type="text" value="" id="mp" name="mp" class="span2">
                                <span class="help-inline" id="help-mp"></span>
							</div>
						</div>	
			
						<div class="control-group" id="group-party_content">
							<label class="control-label" for="party_content">内容</label>
							<div class="controls editor-container">							
								<textarea name="content" id="content" type="text" style="width: 570px;height: 200px;"></textarea>
								<span class="help-inline" id="help-party_content"></span>
							</div>
						</div>					
						
				</div>
			</div>

		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>
<script src="/ueditor/ueditor.all.min.js"></script>
<script src="/ueditor/ueditor.config.js"></script>