<div class="header">
	<h1 class="page-title">报名列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/party">活动报名</a> <span class="divider">/</span></li>
	<li><a href="/party/partyusers">名单列表</a></li>
	<?php if ($this->keywords){ ?>
	    <span class="divider">=></span><li class="active">当前搜索关键词：”<?php echo $this->keywords; ?>“</li>
	<?php }?>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
	<?php 
	if ($this->success)
	{
		echo "<div class=\"alert alert-success\">
        <a class=\"close\" data-dismiss=\"alert\">×</a>
        <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
	}
	?>
		<div class="btn-toolbar">
            <div class="search-well">
                <form class="form-inline" action="" method="post" >
                    <input class="input-xlarge" id="keywords"  name="keywords" type="text" value="<?php echo $this->keywords ;?>" style="margin-right: 5px;">
                    <button class="btn" type="submit" onclick="return checkform();"><i class="icon-search"></i> 搜索</button>
                </form>
            </div>            
			<?php echo $this->bp->genActLink('party_create',$this->bp->act_add,'添加活动/报名');?>
			<div class="btn-group"><hr></div>
		</div>
        <script src="/lib/bootstrap/js/bootstrap-popover.js" type="text/javascript"></script>
        <script src="/lib/bootstrap/js/bootstrap-tooltip.js" type="text/javascript"></script>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="6%">#</th>
						<th>活动ID</th>
						<th>姓名</th>
						<th>电话</th>
						<th>登记时间</th>
						<th>登记IP</th>
						<th style="width: 28px;">删</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
				    foreach ($this->rows as $val) {
				?>
					<tr id="partyusers_<?php echo $val['id'];?>">
						<td><?php echo $val['id'];?></td>
						<td><?php echo $val['parentid'];?></td>
						<td><?php if($this->keywords){ ?>
						<?php echo str_replace($this->keywords,'<font color=red>'.$this->keywords.'</font>',$val['realname']);?>
						<?php }else{ echo $val['realname']; }?></td>
						<?php if($this->keywords){ ?>
						<td><?php echo str_replace($this->keywords,'<font color=red>'.$this->keywords.'</font>',$val['telephone']);?></td>
						<?php }else{?>
						<td><?php echo $val['telephone'];?></td>
						<?php }?>
						<td><?php echo date("Y-m-d H:i:s",$val['addTime']);?></td>
						<td><?php echo $val['addIP'];?></td>
						<td>
						<?php echo $this->bp->genActLink('party_partyusersdelete',$this->bp->act_del,'',array('del_id'=>$val['id']));?>
						</td>
					</tr>
				<?php
				  } 
				}
				?>	
				</tbody>
			</table>
		</div>
		<?php 
		echo $this->paginationcontrol($this->rows,'Sliding','pagination/pagination.phtml',array('parentid'=>$this->parentid,'key'=>$this->keywords,'action'=>'partyusers'));
		?>
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		   <script type="text/javascript">
			 
			 function triggerDel(del_id)
		    {
		   		$("#remove").click(function(){
					
					
					$.post('/party/partyusersdelete?id='+del_id,{'id':del_id},function(data){
	                     alert(data.msg);
						 if (data.req=="ok")
	                     {
							 window.location.reload();
	                     }
	                 },'json');
					
				});		
		    }
		   </script>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除该名单</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>确定删除指定的名单？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="remove" data-dismiss="modal" >确认</button>
			</div>
		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
	</div>
</div>
<script type="text/javascript">
function checkform(){
    var keywords = $('#keywords').val();
    if (keywords == 0 || keywords =='' ) {
        alert('请填写关键词！');
        return false;
    }
}
</script>