<div class="header">
  <h1 class="page-title">编辑账号</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/home">首页</a> <span class="divider">/</span></li>
  <li><a href="/users">账号列表</a> <span class="divider">/</span></li>
  <li class="active">编辑账号  <?php 
        if ($this->row['domain']==0 && $this->row['addtime']==0) echo '<font color="red"><b>( 首次登陆激活，请修改账号密码，提交后将重新登陆 )</b></font>';
        ?></li>
	<li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>
<div class="container-fluid">
  <div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
  <?php 
	if ($this->message)
	{
		echo "<div class=\"alert alert-{$this->message->alert}\">
        <a class=\"close\" data-dismiss=\"alert\">×</a>
        <strong>{$this->message->title}</strong>  {$this->message->message}</div>";
	}
	?>
    <form id="tab" name="editUser" method="post" action="?id=<?php echo $this->row['id'];?>" onSubmit="return clickForm();">
      <div class="btn-toolbar">
        <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
        <div class="btn-group"></div>
      </div>
      <div class="well">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#home" data-toggle="tab">基础配置</a></li>
          <li><a href="#profile" data-toggle="tab">密码设置</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
       <div class="tab-pane active in" id="home">
            <?php 
            if ($this->user->power==3 && $this->id!='1')
            {
            ?>
            <div class="control-group" id="group-power">
              <label class="control-label" for="power">系统审核</label>
              <div class="controls">
                通过  <input type="radio" name="power" id="power_2" value="2" <?php echo $this->row['power']==2?'checked="checked"':'';?> > 
               待审核 <input type="radio" name="power" id="power_0" value="0" <?php echo $this->row['power']==0?'checked="checked"':'';?>>
                <span class="help-inline" id="help-power"></span> </div>
            </div>
            <div class="control-group" id="group-power">
              <label class="control-label" for="power">实名认证</label>
              <div class="controls">
                通过  <input type="radio" name="attestation" id="power_1" value="1" <?php echo $this->row['attestation']==1?'checked="checked"':'';?> > 
               未认证 <input type="radio" name="attestation" id="power_0" value="0" <?php echo $this->row['attestation']==0?'checked="checked"':'';?>>
                <span class="help-inline" id="help-power"></span> </div>
            </div>
		<?php 
            }
		  if (($this->user->power >=2 && $this->user->id != $this->row['id']) || ($this->row['domain']==0 && $this->row['addtime']==0) )
		  {
		  ?>
            <div class="control-group" id="group-username">
              <?php if ($this->row['domain']==0 && $this->row['addtime']==0) {?>
              <label class="control-label" for="username">账号/域名[<font color="red"><b>首次登陆，请务必修改</b></font>]</label>
              <div class="controls">
              <input type="text" value="" name="username" id="username" uid="<?php echo $this->row['id'];?>" lastname="<?php echo $this->row['username'];?>" class="span3">
                <?php }else{?>
              <label class="control-label" for="username">账号/域名</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['username'];?>" name="username" id="username" uid="<?php echo $this->row['id'];?>" lastname="<?php echo $this->row['username'];?>" class="span3">
                <?php }?>
                <span class="help-inline" id="help-username"></span> </div>
            </div>
          <?php 
		  }
		  ?>
		  	<!--选择账户角色-->
			<?php if($this->roles):?>
				<?php if(count($this->roles) > 1):?>
					<div class="control-group" id="group-roleid">
						<label class="control-label" for="roleid">角色</label>
						<div class="controls">
							<select name="roleid" id="roleid">
								<option value="0">---请选择---</option>
								<?php foreach($this->roles as $ek=>$ev):?>
									<option value="<?php echo $ek;?>" <?php if($ek == $this->row['roleid']){echo " selected='selected'";}?>><?php echo $ev;?></option>
								<?php endforeach;?>
							</select>
							<span class="help-inline" id="help-roleid"></span> 
						</div>
					</div>
				<?php else:?>
					<?php foreach($this->roles as $rk=>$rv):?>
						<input type="hidden" name="roleid" value="<?php echo $rk?>">
					<?php endforeach;?>
					
				<?php endif;?>
			<?php else:?>
				<input type="hidden" name="roleid" value="0">
			<?php endif;?>
			
			
			<!--选择账户类别-->
			<?php if($this->user->roleid == 1):?>
				<div class="control-group" id="group-userType">
					<label class="control-label" for="userType">账户类别</label>
					<div class="controls">
						<select name="userType" id="userType">
							<option value="0">---请选择---</option>
							<option value="1" <?php if($this->row['userType'] == 1){echo "selected='selected'";}?>>微站账户</option>
							<option value="2" <?php if($this->row['userType'] == 2){echo "selected='selected'";}?>>微商城账户</option>
						</select>
						<span class="help-inline" id="help-userType"></span> 
					</div>
				</div>
			<?php endif;?>
									
						
            <div class="control-group" id="group-realname">
              <label class="control-label" for="realname">姓名</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['realname'];?>" name="realname" id="realname" class="span3">
                <span class="help-inline" id="help-realname"></span> </div>
            </div>
            <div class="control-group" id="group-email">
              <label class="control-label" for="email">邮箱</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['email'];?>" name="email" id="email" class="span3">
                <span class="help-inline" id="help-email"></span> </div>
            </div>
            <div class="control-group" id="group-tel">
              <label class="control-label" for="tel">电话</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['tel'];?>" name="tel" id="tel" class="span3">
                <span class="help-inline" id="help-tel"></span> </div>
            </div>
            
             <?php 
              if ($this->user->power==3)
              {
              ?>
            <div class="control-group" id="group-shopCount">
              <label class="control-label" for="shopCount">可开门店数</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['shopCount'];?>" name="shopCount" id="shopCount" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-shopCount"></span> </div>
            </div>
            <div class="control-group" id="group-commodityCount">
              <label class="control-label" for="commodityCount">可传商品数</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['commodityCount'];?>" name="commodityCount" id="commodityCount" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-commodityCount"></span> </div>
            </div>
            <script src="/lib/datepicker/WdatePicker.js"></script>
            <div class="control-group" id="group-shopTime">
              <label class="control-label" for="shopTime">到期时间</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['validity']?date('Y-m-d',$this->row['validity']):'';?>" name="validity" id="validity" class="Wdate" onclick="WdatePicker();">
                <span class="help-inline" id="help-shopTime"></span> </div>
            </div>
            <div class="control-group" id="group-remark">
              <label class="control-label" for="remark">备注</label>
              <div class="controls">
                <textarea name="remark" id="remark" rows="5" class="span3"><?php echo $this->row['remark'];?></textarea>
                <span class="help-inline" id="help-remark"></span> </div>
            </div>
            <?php 
              }else
              {
              	  if ($this->row['shopCount'])
              	  {
              	      echo '<b>门店数： '.$this->row['shopCount'].'</b> 门店 <br /><br />';
              	  }elseif($this->row['shopCount']=='0'){
                      echo '<b>门店数：</b> 不限制 <br /><br />';
                  }
              }
              if ($this->row['power']==2)
              {
              	echo "
               <div class=\"control-group\" id=\"group-domain\">
                  <label class=\"control-label\" for=\"domain\"><b>URL：</b></label>    
                <div class=\"controls\">".BASE_URL."/api/</div>     
                </div>
                <div class=\"control-group\" id=\"group-token\">
                  <label class=\"control-label\" for=\"token\"><b>Token：</b></label>
                  <div class=\"controls\">{$this->row['token']}</div>
                </div>
               ";
              }
               ?> 
            </div>
          <div class="tab-pane fade" id="profile">
            <div class="control-group" id="group-password">
              <label class="control-label" for="password">密码</label>
              <div class="controls">
                <input type="password" name="password" id="password" class="span3">
                <span class="help-inline" id="help-password"></span> </div>
            </div>
            <div class="control-group" id="group-repassword">
              <label class="control-label" for="repassword">确认密码</label>
              <div class="controls">
                <input type="password" name="repassword" id="repassword"
									class="span3">
                <span class="help-inline" id="help-repassword"></span> </div>
            </div>
          </div>
        </div>
      </div>
      <script type="text/javascript">
       function parent(pid)
        {
        	$.post("/type/areas?pid="+pid,{},function(data){
                $('#area').html(data);
            	});
        }
        </script> 
      <?php echo $this->partial('partials/homeFooter.phtml');?>
    </form>
  </div>
</div>
