<div class="header">
	<h1 class="page-title">账号列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/users">账号列表</a></li>
	<?php if ($this->keywords){ ?>
	    <span class="divider">=></span><li class="active">当前搜索关键词：”<?php echo $this->keywords; ?>“</li>
	<?php }?>
	<li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
	<?php 
	if ($this->success)
	{
		echo "<div class=\"alert alert-success\">
        <a class=\"close\" data-dismiss=\"alert\">×</a>
        <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
	}
	?>
		<div class="btn-toolbar">
            <div class="search-well">
                <form class="form-inline" action="" method="post" >        
                    <input class="input-xlarge" id="keywords"  name="keywords" type="text" value="<?php echo $this->keywords ;?>" style="margin-right: 5px;">
                    <button class="btn" type="submit" onclick="return checkform();"><i class="icon-search"></i> 搜索</button>
                </form>
            </div>
				 <a href="/users/create" class="btn btn-primary"><i class="icon-plus"></i> 添加账号</a>
				 <?php if ($this->user->power>2) echo '<a href="/users/randuser" class="btn btn-danger"><i class="icon-th-list"></i> 库存系统</a>';?>
				 
			<div class="btn-group"></div>
		</div>
        <script src="/lib/bootstrap/js/bootstrap-popover.js" type="text/javascript"></script>
        <script src="/lib/bootstrap/js/bootstrap-tooltip.js" type="text/javascript"></script>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="6%">#</th>
						<th>用户名</th>
						<th style="">名称</th>
						<th style="">类别</th>
						<th style="">角色</th>
						<?php if ($this->user->power==3) echo "<th>认证</th><th>审核</th><th>登记时间</th><th>到期时间</th><th>登陆数</th>";?>
						<?php if ($this->user->power==2) echo '<th>管理门店</th>';?>
						<th>最后登陆</th>
						<th>最后登录IP</th>
						<th style="">改 / 删</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
				    foreach ($this->rows as $val) {
                        $realname = $val['realname'];
				?>
					<tr title="邮箱: <?php echo $val['email'];?> 
注册时间: <?php echo date("Y-m-d H:i:s",$val['addtime']);?> 
帐号类型:<?php echo $this->power[$val['power']];?>
"
                                         id="users_<?php echo $val['id'];?>">
						<td><?php echo $val['id'];?></td>
						<td><?php if($this->keywords){ ?>
						<?php echo str_replace($this->keywords,'<font color=red>'.$this->keywords.'</font>',$val['username']);?>
						<?php }else{ echo $val['username']; }?></td>
						<?php if($val['remark'] && $this->user->power==3){?>
						<td><a rel="popover" data-content="<?php echo $val['remark'];?>" data-original-title="备注说明"><?php echo $realname;?></a></td>
						<?php }elseif($this->keywords){ ?>
						<td><?php echo str_replace($this->keywords,'<font color=red>'.$this->keywords.'</font>',$realname);?></td>
						<?php }else{?>
						<td><?php echo $realname;?></td>
						<?php }?>
						<td><?php if($val['userType']==1){ echo "微站"; }elseif($val['userType']==2){ echo "微商城"; }else{ echo "<font color=blue>未知</font>";}?></td>
						<td><?php 
                                                echo isset($this->role[$val['roleid']])?$this->role[$val['roleid']]:'<font color=blue>未知</font>';
						?></td>
						<?php if ($this->user->power==3){
						    echo $val['attestation']?"<td>yes</td>":"<td style='color:blue'>no</td>";
						    if($val['power']=='-1' || $val['power']=='0'){ echo "<td style='color:red'>未审</td>"; }else{ echo "<td>已审</td>"; }
						    echo $val['addtime']?"<td>".date("Y-m-d",$val['addtime'])."</td>":'<td></td>';
						    echo $val['validity']?"<td>".date("Y-m-d",$val['validity'])."</td>":'<td></td>';
						    echo "<th>{$val['loginCount']}</th>";
						} 
						?>
						<?php if ($this->user->power==2) echo "<td><a href=\"/shop?action=m&id={$val['id']}\">管理门店</a></td>";?>
						<td><?php echo $val['lastTime']?date("Y-m-d",$val['lastTime']):'';?></td>
						<td><?php echo $val['lastIP'];?></td>
						
						<td>
						<a href="/users/edit?id=<?php echo $val['id'];?>" title="修改编辑"><i class="icon-pencil"></i></a>&nbsp;&nbsp;&nbsp;
						<a href="#myModal" role="button" title="删除" data-toggle="modal" onclick="reid(<?php echo $val['id'];?>);"><i class="icon-remove"></i></a>
						</td>
					</tr>
				<?php
				  } 
				}
				?>	
				</tbody>
			</table>
		</div>
		<?php 
		echo $this->paginationcontrol($this->rows,'Sliding','pagination/pagination.phtml',array('key'=>$this->keywords));
		?>
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		   <script type="text/javascript">
           function reid(i){
                 $('#delid').attr('onclick','deluser('+ i +')');
               }
             function deluser(i)
             {
                 $.post('/users/delete?id='+i,{'id':i},function(data){
                     if (data.isok==true)
                     {
                    	 $('#users_'+i).hide();
                     }
                 },'json');
             }
		   </script>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除账号</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>确定删除指定的账号？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="delid" data-dismiss="modal" >确认</button>
			</div>
		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
	</div>
</div>
<script type="text/javascript">
function checkform(){
    var keywords = $('#keywords').val();
    if (keywords == 0 || keywords =='' ) {
        alert('请填写关键词！');
        return false;
    }
}
</script>