<script src="/lib/datepicker/WdatePicker.js"></script>
<div class="header">
	<h1 class="page-title">库存系统</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/users">账号列表</a><span class="divider">/</span></li>
	<li class="active">库存系统</li>
	<?php if ($this->keywords){ ?>
	    <span class="divider">=></span><li class="active">当前搜索关键词：”<?php echo $this->keywords; ?>“</li>
	<?php }?>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
	<?php 
	if ($this->success)
	{
		echo "<div class=\"alert alert-success\">
        <a class=\"close\" data-dismiss=\"alert\">×</a>
        <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
	}
	?>
		<div class="btn-toolbar">
		    <div class="search-well">
                <form class="form-inline" action="" method="post" >
                    <select name="roles" id="roles" style="width:160px;margin-right: 5px;" >
                      <option value="">选择角色组</option>
                      <?php 
                      $roles=array();
                      if ($this->roles)
                      {
                      	foreach ($this->roles as $val) {
                      		$roles[$val['role_id']]=$val['role_name'];
                            echo "<option value=\"{$val['role_id']}\">{$val['role_name']}</option>";
                      	}
                      }
                      ?>
                      
                    </select>  
					<select name="userType" id="userType" style="width:160px;margin-right: 5px;" >
					   <option value="0">请选择类型</option>
					   <option value="2">微商城账户</option>
					   <option value="1">微站账户</option>
					</select>   
                    <input style="width:50px;margin-right: 5px;" class="input-xlarge" id="num"  name="num" type="text" placeholder="生成数" onkeyup="value=value.replace(/[^\d]/g,'')">
                    <input style="width:50px;margin-right: 5px;" class="input-xlarge" id="commodityCount" name="commodityCount" type="text" placeholder="商品数" onkeyup="value=value.replace(/[^\d]/g,'')">
                    <input style="width:50px;margin-right: 5px;" class="input-xlarge" id="shopCount" name="shopCount" type="text" placeholder="门店数" onkeyup="value=value.replace(/[^\d]/g,'')">
                    <input style="width:80px;margin-right: 5px;" class="input-xlarge" id="passmanage" name="passmanage" type="text" placeholder="验证码" onkeyup="value=value.replace(/[^\d]/g,'')">
                    <input style="width:90px;margin-right: 5px;" type="text" placeholder="使用期限" name="validity" id="validity" class="Wdate" onclick="WdatePicker();">
                    <button class="btn" type="submit" onclick="return checkform();"><i class="icon-user"></i> 配置系统</button>
                </form>
            </div>
				 <a href="/users" class="btn btn-primary">账号列表</a>
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="6%">#</th>
						<th>帐号</th>
						<th>密码</th>
						<th>角色组</th>
						<th>类型</th>
						<th>商品数</th>
						<th>门店数</th>
						<th>到期时间</th>
						<th style="width: 58px;">改 / 删</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
					foreach ($this->rows as $val) {
				?>
					<tr id="users_<?php echo $val['id'];?>">
						<td><?php echo $val['id'];?></td>
						<td><?php echo $val['username'];?></td>
						<td><?php echo $val['pwd'];?></td>
						<td><?php echo isset($roles[$val['roleid']])?$roles[$val['roleid']]:'未知角色';?></td>
						<td><?php if($val['userType']==2){ echo "微电商"; }elseif($val['userType']==1){ echo "微站";}else{ echo "<font color=red>未知</font>";}?></td>
						<td><?php echo $val['commodityCount'];?></td>
						<td><?php echo $val['shopCount'];?></td>
						<td><?php echo $val['validity']?date('Y-m-d',$val['validity']):'';?></td>
						<td>
						<?php echo $this->bp->genActLink('users_edit',$this->bp->act_edit,'修改',array('id'=>$val['id']));?>
						 &nbsp;
						<?php echo $this->bp->genActLink('users_delete',$this->bp->act_del,'',array('del_id'=>$val['id']));?>
						</td>
					</tr>
				<?php
				  } 
				}
				?>	
				</tbody>
			</table>
		</div>
		<?php
		echo $this->paginationcontrol($this->rows,'Sliding','pagination/pagination.phtml',array('action'=>$this->action));
		?>
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		   <script type="text/javascript">			 
			 function triggerDel(del_id)
		     {
		   		$("#remove").click(function(){
					 
					  $.post('/users/delete?id='+del_id,{'id':del_id},function(data){
	                     if (data.isok==true)
	                     {
	                    	 $('#users_'+del_id).hide();
	                     }
	                 },'json');
					
				});		
		    }
		   </script>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除账号</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>确定删除指定的账号？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="remove" data-dismiss="modal" >确认</button>
			</div>
		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
	</div>
</div>
<script type="text/javascript">
function checkform(){
    var num = $('#num').val();
    if (num == 0 || num =='' ) {
        alert('请填写生成数量！');
        return false;
    }

    var roles = $('#roles').val();
    if (roles == 0 || roles =='' ) {
        alert('请选择角色！');
        return false;
    }

    var userType = $('#userType').val();
    if (userType == 0 || userType =='' ) {
        alert('请选择类型！');
        return false;
    }

    var passmanage = $('#passmanage').val();
    if (passmanage == 0 || passmanage =='' ) {
        alert('请填写验证码！');
        return false;
    }
}
</script>