<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;">
<title>注册成功</title>
<style>
body{ font-size:12px; line-height:25px;}
</style>
</head>
<body style=" margin-top:50px;background-color:#70b3f9">
<table border="0" width="70%" align="center" cellpadding="0" cellspacing="0" >
  <tr>
    <td  height="50" style="background-color:#ff9831; text-align:center; font-size:14px; font-weight:bold;line-height:50px;color:#FFF; margin-bottom:5px;">
    注册成功
    </td>
  </tr>
  <tr>
    <td height="100" style="background-color:#FFF; text-align:center;">你的账号已经注册成功，请等待管理员配置系统。</td>
  </tr>
</table>
<div style="text-align:center;">&copy; 游太网络</div>
</body>
</html>