<div class="header">
	<h1 class="page-title">图文素材</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
        <li><a href="/news">消息管理</a> <span class="divider">/</span></li>
        <li class="active">群发消息</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
        <div class="btn-toolbar">
		    <div class="btn-group">
			<a href="/message" role="button"  class="btn btn-primary" ><i class="icon-plus"></i> 返回</a>
            <button class="btn" onclick="onSendSeled()">选中人发送消息</button><button class="btn" onclick="onSendAll()">给所有人发送消息</button>
		    </div>	
        </div>
        <div class="well">
            <div class="form">
                <div class="control-group" style="display:">
                  <label class="control-label" for="optionsRadios">昵称：
                  <div class="controls">
                      <input type="input" name="nickname" /><button onclick='onSearch()' class="btn">搜索</button>
                 </div>
                 </label>
                </div>
                
                <table class="table">
                    <thead>
                        <tr>
                            <th width="5%"><input type='checkbox' onclick='onSelAll()' /></th>
                            <th width="5%">id</th>
                            <th width="10%">昵称</th>
                            <th width="50%">备注</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php 
                    $ids = array();
                    if ($this->fans)
                    {
                        foreach ($this->fans as $val) {
                    ?>
                        <tr>
                            <td><input type="checkbox" class="cb_fan" id="cb_<?php echo $val['id'];?>"/>  </td>
                            <td>
                                <span id="id_<?php echo $val['id'];?>"><?php echo $val['id'];?></span>
                            </td>
                            <td><?php echo $val['nickname'];?></td>
                            <td><?php echo $val['remarkname'];?></td>
                        </tr>
                        <?php 
                        }
                        }
                        ?>
                    </tbody>
                </table>
                <?php 
                    echo $this->paginationcontrol($this->fans,'Sliding','pagination/pagination.phtml',array('action'=>$this->action));
                ?>
        
                <div class="control-group" style="display:none">
                  <label class="control-label" for="radio">性别：
                  <div class="controls">
                      <input type="radio" name="sex" value="3" checked />全部
                      <input type="radio" name="sex" value="1" />男
                      <input type="radio" name="sex" value="2" />女
                 </div>
                 </label>
                </div>
                <div class="control-group" style="display:none">
                  <label class="control-label" for="title">地区：</label>
                  <div class="controls">
                    <select class="selectpicker show-menu-arrow" multiple title="全部城市" data-size="5" data-selected-text-format="count>3" >
                          <?php foreach($this->cities as $city){?>
                          <option><?php echo $city['name']; ?></option>
                          <?php }?>
                    </select>
                  </div>
                </div>
                <div class="control-group" style="display:" >
                  <label class="control-label" for="content">正文：
                  <div class="controls editor-container">
                    <textarea  name="content" class="editor" rows="4"></textarea>
                  </div>
                  </label>
                </div>
            </div>
        </div>
		
		<script type="text/javascript">
        var content_editor = null;
        $(document).ready(function(){
            $('.selectpicker').selectpicker();
            $('.dropdown-menu').css('z-index',1300);
            content_editor = (function init_editor(dom){
                if(dom){
                    editor = new UE.ui.Editor();
                    editor.setOpt('toolbars',[["link"]]);
                    editor.render(dom);
                    return editor;
                }else{
                    return null;
                }
            })($('textarea[name="content"]').get(0));
            if(SCRM.getQueryString('nickname')){
                $('input[name="nickname"]').val(SCRM.getQueryString('nickname'));
            }
            SCRM.setDefaultButton('input[name="nickname"] + button');
        });
        
        function onSendAll(){
            var data_obj = {
                cities:$('.selectpicker').val()?$('.selectpicker').val().join(','):'',
                sex:$("input[name='sex']:checked").val()
            };
            
            var nickname = SCRM.getQueryString('nickname');
            if(nickname){
                data_obj['nickname'] = nickname;
            }
            send(data_obj);
        }
        
        function onSendSeled(){
            var ids = [];
            $('.cb_fan:checked').each(function(){
                ids.push($(this).attr('id').split('_')[1])
            });
            if(ids.length == 0 ){
                SCRM.msg_alert('请选择用户！');
                return;
            }
            var data_obj ={
                "ids":ids.join('|')
            };
            send(data_obj);
        }
        
        function send(post_data){
            if($.trim(content_editor.getPlainTxtEx())  == ''){
                SCRM.msg_alert('请填群发内容!');
                return;
            }
            
            post_data['content'] = content_editor.getPlainTxtEx(),
            
            $.ajax({
                type:'POST',
                url:'/message/sendmass',
                async: true,
                data:post_data,
                success:function(data){
                    typeof data == 'string' && (data = $.parseJSON(data));
                    if (data&& data.code == 'ok') {
                        window.location='/message';
                    }else{
                        SCRM.msg_alert('群发消息出错!');
                    }
                },
                error: function (e) {
                    SCRM.msg_alert('群发消息失败!');
                }
            });
        }
        
        function onSelAll(){
            var cbox = $(event.srcElement || event.target);
            if(cbox.attr('checked')){
                $('.cb_fan').attr('checked',true);
            }else{
                $('.cb_fan').attr('checked',false);
            }
        }
        
        function onSearch(){
            if($.trim($('input[name="nickname"]').val())){
                window.location.search = 'nickname=' +$.trim($('input[name="nickname"]').val());
            }else{
                window.location.search = '';
            }
        }
        </script>
	</div>
</div>
<style>

.editor{
    height:200px;
    width:400px;
}
</style>
<script src="/lib/bootstrap/select/bootstrap-select.min.js"></script>
<link rel="stylesheet" type="text/css" href="/lib/bootstrap/select/bootstrap-select.min.css"></link>
<script src="/ueditor/ueditor.all.min.js"></script>
<script src="/ueditor/ueditor.config_ex.js"></script>