<div class="header">
	<h1 class="page-title">图文素材</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
        <li><a href="/news">消息管理</a> <span class="divider">/</span></li>
        <li class="active">群发消息</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
        <div class="btn-toolbar">
		    <div class="btn-group">
			<a href="/message" role="button"  class="btn btn-primary" data-toggle="modal"><i class="icon-plus"></i> 返回</a>
		    </div>	
        </div>
        <div class="well">
            <div class="form">
                <div class="control-group" style="display:none">
                  <label class="control-label" for="radio">性别：
                  <div class="controls">
                      <input type="radio" name="sex" value="3" checked />全部
                      <input type="radio" name="sex" value="1" />男
                      <input type="radio" name="sex" value="2" />女
                 </div>
                 </label>
                </div>
                <div class="control-group" style="display:none">
                  <label class="control-label" for="title">地区：</label>
                  <div class="controls">
                    <select class="selectpicker show-menu-arrow" multiple title="全部城市" data-size="5" data-selected-text-format="count>3" >
                          <?php foreach($this->cities as $city){?>
                          <option><?php echo $city['name']; ?></option>
                          <?php }?>
                    </select>
                  </div>
                </div>
                <div class="control-group" >
                  <label class="control-label" for="content">正文：
                  <div class="controls editor-container">
                    <textarea  name="content" class="editor" rows="4"></textarea>
                  </div>
                  </label>
                </div>
                <div class="control-group" >
                    <div class="controls">
                        <button class="btn btn-success" onclick="onSend()">发送</button><button class="btn" style="display:none">手机预览</button>
                    </div>
                </div>
            </div>
        </div>
		
		<script type="text/javascript">
        var content_editor = null;
        $(document).ready(function(){
            $('.selectpicker').selectpicker();
            $('.dropdown-menu').css('z-index',1300);
            content_editor = (function init_editor(dom){
                if(dom){
                    editor = new UE.ui.Editor();
                    editor.setOpt('toolbars',[["link"]]);
                    editor.render(dom);
                    return editor;
                }else{
                    return null;
                }
            })($('textarea[name="content"]').get(0));
        });
        
        
        function onSend(){
            if($.trim(content_editor.getPlainTxtEx())  == ''){
                msg_alert('请填群发内容!');
                return;
            }
            
            var data_obj = {
                    content:content_editor.getPlainTxtEx(),
                    cities:$('.selectpicker').val()?$('.selectpicker').val().join(','):'',
                    sex:$("input[name='sex']:checked").val()
            };
            
            $.ajax({
                type:'POST',
                url:'/message/sendmass',
                async: true,
                data:data_obj,
                success:function(data){
                    typeof data == 'string' && (data = $.parseJSON(data));
                    if (data&& data.code == 'ok') {
                        window.location='/message';
                    }else{
                        msg_alert('群发消息出错!');
                    }
                },
                error: function (e) {
                    msg_alert('群发消息失败!');
                }
            });
        }
        </script>
	</div>
</div>
<style>
.editor-container{
   
}

.editor{
    height:200px;
    width:400px;
}
</style>
<script src="/lib/bootstrap/select/bootstrap-select.min.js"></script>
<link rel="stylesheet" type="text/css" href="/lib/bootstrap/select/bootstrap-select.min.css"></link>
<script src="/ueditor/ueditor.all.min.js"></script>
<script src="/ueditor/ueditor.config_ex.js"></script>