<div class="modal" id="dlg_ask_account" style="display:none;">
  <div class="modal-header">
    <h4>群发服务</h4>
  </div>
  <div class="modal-body">
    <input type="checkbox" >启用群发</input>
    <div id="account_form" class="row-fluid" style="display:none">
    <div class="control-group"  >
	  <label class="control-label" for="account">用户名：</label>
	  <div class="controls">
		<input type="text" name="account" data-required data-validate="mail"/>
		</div>
	</div>
    <div class="control-group" >
	  <label class="control-label" for="passwd">密码：</label>
	  <div class="controls">
		<input type="password" name="password" data-required />
	  </div>
	</div>
    </div>
  </div>
  <div class="modal-footer">
    <a href="javascript:history.go(-1);" class="btn">返回</a>
    <a href="#" class="btn btn-primary">保存</a>
  </div>
</div>
<div class="header">
	<h1 class="page-title">群发消息</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
    <li><a href="/message">群发消息</a> <span class="divider">/</span></li>
    <li class="active">任务列表</li>
    <li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
        <div class="btn-toolbar">
		    <div class="btn-group"><a href="/message/addtask" class="btn btn-primary"><i class="icon-plus"></i>群发消息</a></div>
		</div>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="5%">任务ID</th>
						<th width="10%">状态</th>
						<th width="30%">进度</th>
                        <th width="10%">失败数</th>
                        <th width="15%">创建时间</th>
						<!--<th style="width: 50px;">查看</th>-->
					</tr>
				</thead>
				<tbody>
				<?php 
                $ids = array();
				if ($this->rows)
				{
                    //任务状态0-初始,1-执行中,2-执行成功,3-执行失败。
                    $status = array(
                        '<div>unknown</div>',
                        '<div class="icon-time">等待执行</div>',
                        '<div class="icon-refresh">执行中</div>',
                        '<div>执行失败</div>',
                        '<div class="icon-ok-circle">执行完毕</div>'
                    );
					foreach ($this->rows as $val) {
                        if($val['status'] <=2)
                            array_push($ids,$val['id']);
				?>
					<tr id="news_<?php echo $val['id'];?>">
						<td>
                            <div class="rows-fluid">
								<span id="id_<?php echo $val['id'];?>"><?php echo $val['id'];?></span>
                            </div>
						</td>
						<td><div id="status_<?php echo $val['id'];?>"><?php echo $status[$val['status']];?></div></td>
						<td>
                            <div class="progress" id="progress_<?php echo $val['id'];?>">
                              <div  class="bar" style="width: <?php echo 100*$val['sent_count']/$val['total_count'];?>%;"><?php echo $val['sent_count'].'/'.$val['total_count'];?></div>
                            </div>
                        </td>
						<td><span id="fail_<?php echo $val['id'];?>"><?php echo ((int)$val['sent_count']-(int)$val['suc_count']);?></span></td>
                        <td><?php echo $val['create_time'];?></td>
						<td>
						<!--<a href="/message/task/<?php echo $val['id'];?>" title="查看"><i class="icon-search"/></a>-->
						</td>
					</tr>
					<?php 
					}
					}
					?>
				</tbody>
			</table>
		</div>
		<?php 
            echo $this->paginationcontrol($this->rows,'Sliding','pagination/pagination.phtml',array('action'=>$this->action));
		?>
		<script type="text/javascript">
        var account_info = <?php echo json_encode($this->account);?>;
        var ids = <?php echo json_encode($ids);?>;
        $(document).ready(function(){
            $("a[href='#delete']").on('click',function(){
                $('#btn_del_news').attr('data-id',$(this).attr('data-id'));
                $('#dlg_del_news').modal('show');
            });
            
            $('#btn_del_news').on('click',function(){
                 var self = $(this);
                 var id = self.attr('data-id');
                 $.post('/news/delete?id='+id,{'id':id},function(data){
                     if (data.code=='ok')
                     {
                    	 $('#news_'+id).hide();
                     }
                 },'json');
            });
            
            if(!account_info){
                $(document).initCheck({
                    eachValidField : function() {
                        $(this).css('border-color','#468847');
                    },
                    eachInvalidField : function() {
                        $(this).css('border-color','#b94a48');
                    },
                    valid:function(){
                        var args = Array.prototype.slice.call(arguments);
                        if(args.length >= 3){
                            args[2].each(function(){
                                $(this).css('border-color','');
                            });
                        }
                    }
                });
            
                $('#dlg_ask_account input[type="checkbox"]').click(function(){
                    if($(this).attr('checked')){
                        $('#account_form').show();
                    }else{
                        $('#account_form').hide();
                    }
                });
                
                $('#dlg_ask_account .btn-primary').click(function(){
                    if(false == $('#account_form').check()){
                        return;
                    }
                    var data_obj={
                        'account':$('#dlg_ask_account input[name="account"]').val(),
                        'password':$('#dlg_ask_account input[name="password"]').val()
                    };
                    $.ajax({
                        type: 'post',
                        url: '/message/updateaccount',
                        data:data_obj,
                        async: true,
                        cache:false,
                        success: function (n) {
                            $('#dlg_ask_account').modal('hide');
                        }
                    });
                });
                $('#dlg_ask_account').modal();
            }
            startUpdater(); 
        });

        function getStatusStr(code){
            code = parseInt(code)
            var stats = [
                    '<div>unknown</div>',
                    '<div class="icon-time">等待执行</div>',
                    '<div class="icon-refresh">执行中</div>',
                    '<div>执行失败</div>',
                    '<div class="icon-ok-circle">执行完毕</>'
                ];
            return stats[code];
        }
        
        function updateTaskInfo(task){
            if(!task){
                return;
            }
            $('#status_' + task['id']).html(getStatusStr(task['status']));
            var bar = $('#progress_' + task['id'] + ' .bar');
            bar.css('width',100*(parseInt(task['sent_count'])/parseInt(task['total_count'])) + "%")
            bar.html(task['sent_count']+'/'+task['total_count']);
            $('#fail_' + task['id']).html((task['sent_count']-task['suc_count']));
        }
        
        function startUpdater(){
            var post_data = {
            "ids":ids.join('|')
            };
            window.setInterval(function(){
                $.ajax({
                    type: 'post',
                    url: '/message/taskinfo',
                    data:post_data,
                    async: true,
                    cache:false,
                    success: function (n) {
                        typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
                            for(var i=n.data.length;i--;){
                                if($.inArray(n.data[i]['id'],ids) > -1){
                                    updateTaskInfo(n.data[i]);
                                }
                            }
                        }else{
                            msg_alert(n.msg);
                        }
                    }
                });
            }, 5000);
        }
        </script>
		<?php 
		echo $this->partial('partials/homeFooter.phtml');
		?>
	</div>
</div>