
<div id="dlg_add_rule" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 id="myModalLabel">增加规则</h4>
  </div>
  <div class="modal-body">
	<input type="text" id="new_rule_name" placeholder="输入规则名" data-required="true" data-trim="true"/>
  </div>
  <div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
	<button class="btn btn-primary" id="btn_add_rule">确定</button>
  </div>
</div>

<div id="dlg_edit_rule" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 id="myModalLabel">编辑规则</h4>
  </div>
  <div class="modal-body">
	<input type="text" placeholder="输入规则名" data-required="true" data-trim="true"/>
	<input type="hidden" value='' />
  </div>
  <div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
	<button class="btn btn-primary" id="btn_edit_rule">确定</button>
  </div>
</div>

<div id="dlg_add_keyword" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 id="myModalLabel">增加关键字</h4>
  </div>
  <div class="modal-body">
	<input type="text" id="new_rule_name" placeholder="关键字" data-required="true" data-trim="true" />
    <label>完全匹配<input type="checkbox" name="match_type" /></label>
	<input type="hidden" name="ids" />
  </div>
  <div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
	<button class="btn btn-primary" id="btn_add_keyword">确定</button>
  </div>
</div>


<div id="dlg_add_reply_text" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 id="myModalLabel">增加回复文本</h4>
  </div>
  <div class="modal-body">
     <div class="control-group" >
      <label class="control-label" for="title">标题(*)：</label>
      <div class="controls">
        <input type="text" name="title" placeholder="标题" data-required="true" data-trim="true"/>
        </div>
    </div>
    <div class="control-group" >
      <label class="control-label" for="description">描述(*)：</label>
      <div class="controls editor-container">
        <textarea name="description"  rows="4" class="editor" placeholder="文本内容"></textarea>
        </div>
    </div>
	<input type="hidden" name="ids" />
  </div>
  <div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
	<button class="btn btn-primary" id="btn_add_reply_text">确定</button>
  </div>
</div>


<div id="dlg_edit_keyword" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 id="myModalLabel">编辑关键字</h4>
  </div>
  <div class="modal-body">
	<input type="text" placeholder="关键字" data-required="true" data-trim="true" /><label>完全匹配<input type="checkbox" name="match_type" /></label>
	<input type="hidden" />
  </div>
  <div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
	<button class="btn btn-primary" id="btn_edit_keyword">确定</button>
  </div>
</div>


<div id="dlg_edit_reply_text" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 id="myModalLabel">编辑回复项</h4>
  </div>
  <div class="modal-body editor-container">
    <div class="control-group" >
      <label class="control-label" for="title">标题(*)：</label>
      <div class="controls">
        <input type="text" name="title" placeholder="标题" data-required="true" data-trim="true" />
        </div>
    </div>
	<div class="control-group" >
      <label class="control-label" for="description">描述(*)：</label>
      <div class="controls editor-container">
        <textarea name="description"  rows="4" class="editor" placeholder="文本内容"></textarea>
        </div>
    </div>
    
	<input type="hidden" name="ids" />
  </div>
  <div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
	<button class="btn btn-primary" id="btn_edit_reply_text">确定</button>
  </div>
</div>


<div id="dlg_add_reply_news"  class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 id="myModalLabel">增加回复消息</h4>
  </div>
  <div class="modal-body">
	<div class="btn-group">
		<button class="btn btn-page-prev">上一页</button>
		<button class="btn btn-page-next">下一页</button>
	</div>
	<div id="news_list">
	</div>
	<div class="btn-group">
		<button class="btn btn-page-prev">上一页</button>
		<button class="btn btn-page-next">下一页</button>
	</div>
  </div>
  <div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
	<button class="btn btn-primary" id="btn_add_reply_news">确定</button>
  </div>
</div>

<div class="header">
  <h1 class="page-title">关键词自动回复</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/home">首页</a> <span class="divider">/</span></li>
  <li><a href="/news">消息管理</a> <span class="divider">/</span></li>
  <li class="active">关键词自动回复</li>	
  <li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>
<div class="container-fluid">
  <div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
  	<div class="btn-toolbar">
		    <div class="btn-group">
			<a href="#dlg_add_rule" role="button"  class="btn btn-primary" data-toggle="modal"><i class="icon-plus"></i> 添加规则</a>
		    </div>	
    </div>
	  <div class="well">
		<div class="rule-list row-fluid">	
		</div>
	  </div>
	</div>
</div>
<script id="templ_news_list" type="text/html"><#TS#/*TEMPLATES*/#TS#>
<table class="table-hover text-center">
	<thead>
		<th class="span5">标题</th><th class="span1">选择</th>
	</thead>
	<tbody >
	<#TS#
		for(var i=0;news && i<news.length;i++){
	#TS#>
	<tr><td><span><#TS#=news[i].title#TS#></span></td><td><button class="btn" data-id="<#TS#=rule_id +'_'+news[i].id#TS#>">选取</button></td></tr>
	<#TS#
		}
	#TS#>
	</tbody>
</table>
</script>
<script id="templ_keyword_item" type="text/html"><#TS#/*TEMPLATES*/#TS#>
<li><span data-id="<#TS#=autoreply_id+'_'+id+'_'+type#TS#>"><#TS#=keyword#TS#></span>
	<div class="rule_opt pull-right"><a href="#edit" data-id="<#TS#=autoreply_id+'_'+id+'_'+type#TS#>">编辑</a>|<a href="#delete" data-id="<#TS#=autoreply_id+'_'+id+'_'+type#TS#>">删除</a></div>
</li>
</script>

<script id="templ_reply_item" type="text/html"><#TS#/*TEMPLATES*/#TS#>
<li><#TS#=type==2?'[文本]':'[图文]'#TS#>&nbsp;<span data-id="<#TS#=autoreply_id+'_'+id+'_'+type#TS#>"><#TS#=title#TS#></span><textarea style="display:none"><#TS#=description#TS#></textarea>
	<div class="rule_opt pull-right">
	<#TS#
		if(type == 2){
	#TS#>
		<a href="#edit" data-id="<#TS#=autoreply_id+'_'+id+'_'+type#TS#>">编辑</a>|
	<#TS#
		}
	#TS#>
	<a href="#delete" data-id="<#TS#=autoreply_id+'_'+id+'_'+type#TS#>" >删除</a></div>
</li>
</script>

<script id="templ_rule_item" type="text/html"><#TS#/*TEMPLATES*/#TS#>
<#TS#
	for(var i=0;i<rules.length;i++){
#TS#>
<div class="rule-item" id="rule_item_<#TS#=rules[i].id#TS#>">
	<div class="row-fluid">
		<div class="rule_title"><b>规则：</b><span><#TS#=rules[i].name#TS#></span><span class="rule_title_opt"><a href="#edit" data-id="<#TS#=rules[i].id#TS#>" >编辑</a>|<a href="#delete" data-id="<#TS#=rules[i].id#TS#>">删除</a></span></div>
		<div class="span5">
				<div class="keywords_title"><span><b>关键词：</b></span></div>
				<ol class="keword_list">
					<#TS#
						for(var j=0;rules[i]['keywords'] && j<rules[i]['keywords'].length;j++){
					#TS#>
					<#TS#=tmpl_parser('#templ_keyword_item',rules[i]['keywords'][j])#TS#>
					<#TS#
						}
					#TS#>
				</ol>
				<div class="btn_keywords_add"><button class="btn btn-small" data-id="<#TS#=rules[i].id#TS#>">添加关键字</button></div>
		</div>
		<div class="span5" >
			<div class="reply_title"><b>自动回复内容：</b><span class="rule_title_opt" style="display:none"><a href="#" >编辑</a></span></div>
			<ol class="reply_list">
					<#TS#
						for(var j=0;rules[i]['news'] && j<rules[i]['news'].length;j++){
					#TS#>
					<#TS#=tmpl_parser('#templ_reply_item',rules[i]['news'][j])#TS#>
					<#TS#
						}
					#TS#>
			</ol>
			<div class="btn_reply_add btn-group">
				<button class="btn btn-small btn-reply-text" data-id="<#TS#=rules[i].id#TS#>">添加回复文本</button>
				<button class="btn btn-small btn-reply-news" data-id="<#TS#=rules[i].id#TS#>">添加回复图文</button>
			</div>
		</div>
	</div>
</div>
<#TS#
}
#TS#>
</script>
<script>
	var TMPL={};
    var add_reply_text_editor
        ,edit_reply_text_editor;
        
	function show_rules(rule_obj)
	{
		$('.rule-list').html(tmpl_parser('#templ_rule_item',rule_obj));
		rules_bind_event();
	}
	
	function rules_bind_event()
	{
        $('.btn_keywords_add button').unbind();
		$('.btn_keywords_add button').bind('click',function(){
				$("#dlg_add_keyword input[type='hidden']").val($(event.srcElement || event.target).attr('data-id'));
				$('#dlg_add_keyword').modal('show')
			});
			
		
		$('.btn_reply_add button').filter('.btn-reply-text').unbind();
		$('.btn_reply_add button').filter('.btn-reply-text').bind('click',function(){
			$("#dlg_add_reply_text input[type='hidden']").val($(event.srcElement || event.target).attr('data-id'));
			$('#dlg_add_reply_text').modal('show')
		});
		
		/*选择news回复*/
		$('.btn_reply_add button').filter('.btn-reply-news').unbind();
		$('.btn_reply_add button').filter('.btn-reply-news').bind('click',function(){
			var rule_id = $(event.srcElement || event.target).attr('data-id');
			/*加载news列表*/
			var  load_news_list = function(page){
				var page_size = 10;
				$.ajax({
					type: 'get',
					url: '/news/list?page=' + page + "&page_size=" + page_size,
					async: true,
					cache:false,
					success: function (n) {
						typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
							$('#news_list').html(tmpl_parser('#templ_news_list',{'news':n.data,'rule_id':rule_id}));
							$('#news_list button').bind('click',function(){
								var ids = $(event.srcElement || event.target).attr('data-id').split('_');
								var data_obj = {
									'autoreply_id': ids[0],
									'news_id': ids[1],
									'type': 1/*图文消息*/
								};
								$.ajax({
										type: 'POST',
										url: '/autoreply/addreply',
										async: true,
										cache:false,
										data:data_obj,
										success: function (n) {
											typeof n == 'string' && (n = $.parseJSON(n));
											if (n && n.code == 'ok') {
												$('#rule_item_'+data_obj['autoreply_id']+" .reply_list").append(tmpl_parser('#templ_reply_item',n.data));
												rules_bind_event();
											}else{
												alert("添加图文回复消息出错!");/*lwq:alert统一换成界面出错提示*/
											}
										},
										error: function (e) {
											alert('添加图文回复消息出错');//lwq:alert不友好，换成统一界面文本提示。
										}
									});
								$('#dlg_add_reply_news').modal('hide');
							});
						}else{
							alert("加载消息列表出错!");/*lwq:alert统一换成界面出错提示*/
						}
						
						$('.btn-page-next').unbind();/*避免重复绑定事件*/
						$('.btn-page-next').one('click',function(){
							if(n.data && page * page_size < n.total){load_news_list(page+1)};
						});
						
						$('.btn-page-prev').unbind();
						$('.btn-page-prev').bind('click',function(){
							if(page > 1)load_news_list(page-1);
						});
					},
					error: function (e) {
						alert('加载消息列表出错');//lwq:alert不友好，换成统一界面文本提示。
						$('.btn-page-prev').attr('diabled',true);
						$('.btn-page-next').attr('diabled',true);
					}
				});
			};
			$('#dlg_add_reply_news').modal('show');
			load_news_list(1);
		});
			
		/*绑定编辑关键字*/
		$(".keword_list a[href='#edit']").unbind();
		$(".keword_list a[href='#edit']").bind('click',function(){
			var ids = $(event.srcElement || event.target).attr('data-id');
			$("#dlg_edit_keyword input[type='text']").val($(event.srcElement || event.target).parent().parent().find('span').html());
			$("#dlg_edit_keyword input[type='hidden']").val(ids);
			$("#dlg_edit_keyword input[type='checkbox']").attr('checked',ids.split('_')[2]==='1');
			$("#dlg_edit_keyword").modal('show')
		});
		
		/*绑定删除关键字*/
		$(".keword_list a[href='#delete']").unbind();
		$(".keword_list a[href='#delete']").bind('click',function(){
			var src_obj = $(event.srcElement || event.target);
			var ids = src_obj.attr('data-id').split('_');
			var data_obj={
				'id':ids[1],
				'autoreply_id':ids[0]
				};
			$.ajax({
					type: 'POST',
					url: '/autoreply/delkeyword',
					async: true,
					data: data_obj,
					success: function (n) {
						typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
							/*移除关键字项*/
							src_obj.parent().parent().remove();
						}else{
							alert("编辑规则出错!");/*lwq:alert统一换成界面出错提示*/
						}
					},
					error: function (e) {
						alert('编辑规则失败！');//lwq:alert不友好，换成统一界面文本提示。
					}
				});
		});
		
		/*绑定删除关键字*/
		$(".rule_title_opt a[href='#delete']").unbind();
		$(".rule_title_opt a[href='#delete']").bind('click',function(){
			var data_obj={
				'id':parseInt($(event.srcElement || event.target).attr('data-id'))
				};
			$.ajax({
					type: 'POST',
					url: '/autoreply/delete',
					async: true,
					data: data_obj,
					success: function (n) {
						typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
							/*移除关键字项*/
							$('#rule_item_' + data_obj['id']).remove();
						}else{
							alert("编辑规则出错!");/*lwq:alert统一换成界面出错提示*/
						}
					},
					error: function (e) {
						alert('编辑规则失败！');//lwq:alert不友好，换成统一界面文本提示。
					}
				});
		});
		
		/*绑定编辑回复内容*/
		$(".reply_list a[href='#edit']").unbind();
		$(".reply_list a[href='#edit']").bind('click',function(){
			var src_obj = $(this);
			var ids = src_obj.attr('data-id');
			if(ids.split('_')[2] ==2){/*文本消息*/
				$('#dlg_edit_reply_text input[type="hidden"]').val(ids);
				$('#dlg_edit_reply_text input[type="text"]').val(src_obj.parent().parent().children('span').html());
				if(edit_reply_text_editor)
                    edit_reply_text_editor.setContent(src_obj.parent().parent().children('textarea').val());
                //$('#dlg_edit_reply_text textarea').val(src_obj.parent().parent().children('input[type="hidden"]').val());
				$('#dlg_edit_reply_text').modal('show')
			}else{
				//$('#dlg_edit_reply_news').modal('show')
			}
			
		});
		
		/*绑定删除关键字*/
		$(".reply_list a[href='#delete']").unbind();
		$(".reply_list a[href='#delete']").bind('click',function(){
			var ids = $(event.srcElement || event.target).attr('data-id').split('_');
			var data_obj={
				'id':ids[1],
				'autoreply_id':ids[0]
				};
			$.ajax({
					type: 'POST',
					url: '/autoreply/delreply',
					async: true,
					data: data_obj,
					success: function (n) {
						typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
							/*移除关键字项*/
							$('#rule_item_' + data_obj['autoreply_id']+" ol[class='reply_list'] span[data-id='"+ids.join('_')+"']").parent().remove();
						}else{
							alert("编辑规则出错!");/*lwq:alert统一换成界面出错提示*/
						}
					},
					error: function (e) {
						alert('编辑规则失败！');//lwq:alert不友好，换成统一界面文本提示。
					},
				})
		});
		
		
		$(".rule_title_opt a[href='#edit']").unbind();
		$(".rule_title_opt a[href='#edit']").bind('click',function(){
			$('#dlg_edit_rule input[type="text"]').val($(event.srcElement || event.target).parent().prev().html());
			$('#dlg_edit_rule input[type="hidden"]').val($(this).attr('data-id'));
			$('#dlg_edit_rule').modal('show')
		});
	}
	
	Rules = {
		rules:[],
		add:function(rule){
			if(!rule)return;
			for(var i=this.rules.length;i--;){
				if(rule.id == this.rules[i].id)
					return false;
			}
			this.rules.push(rule);
			return true;
		}
	};
    
	$(document).ready(
		function(){
            /*初始化校验规则*/
            $(document).initCheck({
                eachValidField : function() {
                    $(this).css('border-color','#468847');
                },
                eachInvalidField : function() {
                    $(this).css('border-color','#b94a48');
                },
                valid:function(){
                    var args = Array.prototype.slice.call(arguments);
                    if(args.length >= 3){
                        args[2].each(function(){
                            $(this).css('border-color','');
                        });
                    }
                }
            });
            
            function init_editor(dom){
                if(dom){
                    editor = new UE.ui.Editor();
                    editor.setOpt('toolbars',[["link"]]);
                    editor.render(dom);
                    return editor;
                }else{
                    return null;
                }
            }
            
            add_reply_text_editor = init_editor($('#dlg_add_reply_text textarea[name="description"]').get(0));
            edit_reply_text_editor = init_editor($('#dlg_edit_reply_text textarea[name="description"]').get(0));
            
			Rules.rules = <?php echo json_encode($rules)?>;
			show_rules(Rules);
			$('#btn_add_rule').bind('click',function(){
				var rule_obj ={'name':$('#new_rule_name').val()};
				if(!$('#dlg_add_rule').check()){
                    return;
                }
                $('#dlg_add_rule').modal('hide')
				$('#new_rule_name').val('');
                $.ajax({
					type: 'POST',
					url: '/autoreply/add',
					async: true,
					data: rule_obj,
					success: function (n) {
						typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
							$('.rule-list').append(tmpl_parser('#templ_rule_item',{rules:[n.data]}));
							rules_bind_event();
						}else{
							alert("添加规则出错!");/*lwq:alert统一换成界面出错提示*/
						}
					},
					error: function (e) {
						alert('保存失败！');//lwq:alert不友好，换成统一界面文本提示。
					},
				})
			});
			/**/
			$('#btn_edit_rule').bind('click',function(){
				var rule_obj ={
					'name':$('#dlg_edit_rule input').val()
				};
				var rule_id = parseInt($('#dlg_edit_rule input[type="hidden"]').val());
                if(!$('#dlg_edit_rule').check()){
                    return;
                }
				$('#dlg_edit_rule').modal('hide')
				$.ajax({
					type: 'POST',
					url: '/autoreply/edit/?id=' + rule_id,
					async: true,
					data: rule_obj,
					success: function (n) {
						typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
							$('#rule_item_' + rule_id+" span:first").html(rule_obj.name);
						}else{
							alert("编辑规则出错!");/*lwq:alert统一换成界面出错提示*/
						}
					},
					error: function (e) {
						alert('编辑规则失败！');//lwq:alert不友好，换成统一界面文本提示。
					},
				})
			});
			/*编辑关键字按钮*/
			$('#btn_edit_keyword').bind('click',function(){
				var ids = $("#dlg_edit_keyword input[type='hidden']").val().split('_');
				var data_obj ={
					'keyword':$("#dlg_edit_keyword input[type='text']").val(),
					'type':($("#dlg_edit_keyword input[type='checkbox']").attr('checked')?1:0),
					'autoreply_id':parseInt(ids[0]),
					'id':parseInt(ids[1])
				};
                if(!$('#dlg_edit_keyword').check()){
                    return;
                }
				$('#dlg_edit_keyword').modal('hide')
				$.ajax({
					type: 'POST',
					url: '/autoreply/editkeyword',
					async: true,
					data: data_obj,
					success: function (n) {
						typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
                            var old_ids = ids.join('_');
							$('#rule_item_' + data_obj['autoreply_id']+" span[data-id='"+old_ids+"']").html(data_obj['keyword']);
                            ids[2] = data_obj.type;
                            $('#rule_item_' + data_obj['autoreply_id']+" span[data-id='"+old_ids+"']").attr('data-id',ids.join('_'));
                            $('#rule_item_' + data_obj['autoreply_id']+" a[data-id='"+old_ids+"']").attr('data-id',ids.join('_'));
                            
						}else{
							alert("编辑规则出错!");/*lwq:alert统一换成界面出错提示*/
						}
					},
					error: function (e) {
						alert('编辑规则失败！');//lwq:alert不友好，换成统一界面文本提示。
					},
				})
			});
			/*添加关键字按钮*/
			$('#btn_add_keyword').bind('click',function(){
				var data_obj ={
					'autoreply_id':$("#dlg_add_keyword input[type='hidden']").val(),
					'keyword':$("#dlg_add_keyword input[type='text']").val(),
					'type':($("#dlg_add_keyword input[type='checkbox']").attr('checked')?1:0)
				};
                
                if(!$('#dlg_add_keyword').check()){
                    return;
                }
				$('#dlg_add_keyword').modal('hide');
               $("#dlg_add_keyword input[type='text']").val('');
				$("#dlg_add_keyword input[type='checkbox']").attr('checked',false);
				
				$.ajax({
					type: 'POST',
					url: '/autoreply/addkeyword',
					async: true,
					data: data_obj,
					success: function (n) {
						typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
							$('#rule_item_'+data_obj['autoreply_id']+" .keword_list").append(tmpl_parser('#templ_keyword_item',n.data));
							rules_bind_event();
						}else{
							alert("添加规则出错!");/*lwq:alert统一换成界面出错提示*/
						}
					},
					error: function (e) {
						alert('保存失败！');//lwq:alert不友好，换成统一界面文本提示。
					},
				})
			});
			
			/*添加回复文本按钮*/
			$('#btn_add_reply_text').bind('click',function(){
				var data_obj ={
					'autoreply_id':$("#dlg_add_reply_text input[type='hidden']").val(),
					'description':add_reply_text_editor.getPlainTxtEx(),
					'title':$("#dlg_add_reply_text input[type='text']").val(),
					'type':2/*文本消息*/
				};
				if(!$('#dlg_add_reply_text').check() || add_reply_text_editor.getPlainTxtEx()==''){
                    return;
                }
                $('#dlg_add_reply_text').modal('hide');
				//$("#dlg_add_reply_text textarea").val('');
                if(add_reply_text_editor)
                    add_reply_text_editor.setContent('')
				$("#dlg_add_reply_text input[type='text']").val('')
				
				$.ajax({
					type: 'POST',
					url: '/autoreply/addreply',
					async: true,
					data: data_obj,
					success: function (n) {
						typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
							$('#rule_item_'+data_obj['autoreply_id']+" .reply_list").append(tmpl_parser('#templ_reply_item',n.data));
							rules_bind_event();
						}else{
							alert("添加规则出错!");/*lwq:alert统一换成界面出错提示*/
						}
					},
					error: function (e) {
						alert('保存失败！');//lwq:alert不友好，换成统一界面文本提示。
					},
				})
			});
			
			/*编辑回复文本按钮*/
			$('#btn_edit_reply_text').bind('click',function(){
				var ids = $("#dlg_edit_reply_text input[type='hidden']").val().split('_');
				var data_obj ={
					'autoreply_id':ids[0],
					'id':ids[1],
					'description':edit_reply_text_editor.getPlainTxtEx(),
					'title':$("#dlg_edit_reply_text input[type='text']").val(),
					'type':2/*文本消息*/
				};
                if(!$('#dlg_edit_reply_text').check() || edit_reply_text_editor.getPlainTxtEx()==''){
                    return;
                }
                
				$('#dlg_edit_reply_text').modal('hide');
				//$("#dlg_edit_reply_text textarea").val('');
                if(edit_reply_text_editor)
                    edit_reply_text_editor.setContent('');
				$("#dlg_edit_reply_text input[type='text']").val('')
				
				$.ajax({
					type: 'POST',
					url: '/autoreply/editreply',
					async: true,
					data: data_obj,
					success: function (n) {
						typeof n == 'string' && (n = $.parseJSON(n));
						if (n && n.code == 'ok') {
							item_dom_obj = $('#rule_item_' + data_obj['autoreply_id']+" ol[class='reply_list'] span[data-id='"+ids.join('_')+"']").parent();
							if(data_obj['type'] == 2){/*文本消息*/
							item_dom_obj.children('span').html(data_obj['title']);
							item_dom_obj.children('input[type="hidden"]').val(data_obj['description']);
							}
						}else{
							alert("添加规则出错!");/*lwq:alert统一换成界面出错提示*/
						}
					},
					error: function (e) {
						alert('保存失败！');//lwq:alert不友好，换成统一界面文本提示。
					},
				})
			});
			
		}
	);
	
	
</script>
<style>
.rule-item{
	border-bottom:1px solid #eee;
	padding-top:10px;
	padding-bottom:10px;
}
.rule_opt{
	
}

.rule_title_opt{
	padding-left:5px;
	color:#999;
}

.reply_list li,.keword_list li{
	border-bottom:1px dashed #eee;
}

.keword_list a,.reply_list a{
	color:#09f
}

.keword_list a:hover,.reply_list a:hover{
	color:#09f
}

.editor-container{
    /*height:150px;*/
}

.editor{
    height:200px;
}

</style>
<script src="/ueditor/ueditor.all.min.js"></script>
<script src="/ueditor/ueditor.config_ex.js"></script>