<FORM id=uploadForm encType=multipart/form-data method=post action="">
<INPUT id=uploadFile class=uploadFile onchange=upload() type=file name=uploadfile> <INPUT class=formId type=hidden name=formId val=""> 
</FORM>
<SCRIPT type=text/javascript>
      document.domain = location.hostname.match(/[^\.]*?\.[^\.]*?$/);
      
      var 
        url = window.location.href,
        type = url.match(/[\?&]type=([^&]*)/),
        token = url.match(/[\?&]token=([^&]*)/),
        formId = url.match(/[\?&]formId=([^&]*)/);
        //d = top.W.d,
        //suc = top.W.suc,
        //err = top.W.err;

      //type = type && type[1] || 0;
      //formId = formId && formId[1];
      //token = token && token[1];
      
      var _allowType = {
        ".bmp":2, ".png":2, ".jpeg":2, ".jpg":2, ".gif":2,
        ".mp3":3, ".wma":3, ".wav":3, ".amr":3,
        ".rm":4, ".rmvb":4, ".wmv":4, ".avi":4, ".mpg":4, ".mpeg":4, ".mp4":4
      };
      var errMsg = {
        "0" : '图片格式必须为以下格式：bmp, png, jpeg, jpg, gif<br/>'
              + '语音格式必须为以下格式：mp3, wma, wav, amr<br/>'
              + '视频格式必须为以下格式：rm, rmvb, wmv, avi, mpg, mpeg, mp4<br/>',
        "2" : '图片格式必须为以下格式：bmp, png, jpeg, jpg, gif',
        "3" : '语音格式必须为以下格式：mp3, wma, wav, amr',
        "4" : '视频格式必须为以下格式：rm, rmvb, wmv, avi, mpg, mpeg, mp4'
      }
      function _checkFileType(_fileName, _type){
        var _ext = _fileName.substr(_fileName.lastIndexOf(".")).toLowerCase(),
          _res = _allowType[_ext];
        
        if (_type == 0) {
          return !!_res;
        } else {
          return _type == _res;
        }
      }
      function upload(){
        var _fileName = jQuery.trim(jQuery('#uploadFile').val());
        if (!_fileName || _fileName == ""){  // 提交前的再次检测
          err('请选择文件上传');
          return false;
        }
        if (!_checkFileType(_fileName, type)){
          var content = "";
          d.show({
            'title':'上传文件格式错误',
            'content':errMsg[type],
            'width':450,
            'height':75,
            'noCancle':true,
            'onok':function(){}
          });
          return false;
        }
        jQuery("#uploadForm").attr("action", "/cgi-bin/uploadmaterial?cgi=uploadmaterial&type=2&token=973970532&t=iframe-uploadfile&lang=zh_CN" + "&formId=" + formId);
        suc('上传中...请耐心等候');
        jQuery('#uploadForm').submit();
      }
</SCRIPT>
