<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<title>登陆</title>
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" />
<meta name="format-detection" content="telephone=no" />
<link type="text/css" rel="stylesheet" href="/css/style.css" />
<script type="text/javascript" src="/js/jquery.min.js"></script>
</head>

<body>
	<!--头部-->
	<header class="ts1">
		<a class="u_back fl" href="/">首页</a>
	</header>
	<!--主体-->
	<div class="main">
		<form method="post" action="" onsubmit="return checkform();">
			<div class="p_mod o_address">
				<h2 class="p_mod_title">登陆</h2>
				<div id="city">
					<ul>
						<li><strong>用户名：</strong> <input type="text" placeholder="请输入用户名" id="username" name="username" value="">
						</li>
						<li><strong>密&nbsp;&nbsp;码 ：</strong> <input type="password" placeholder="请输入密码" id="password" name="password" value="">
						</li>
					</ul>
				</div>
			</div>
			<div class="o_btn clearfix">
				<input type="button" class="o_btn_back ts1" onclick="window.location.href='/user/register';" value="三秒注册">
				<input type="submit" class="o_btn_submit ts1" value="登陆">
			</div>
		</form>
	</div>
	<!--底部-->
	<?php echo $this->partial ( 'partials/footer.phtml');?>
	<script type="text/javascript">
		function checkform() {
			var username=$('#username').val();
			if (username=='')
				{
					alert('请输入用户名');
					return false;
				}
			var password=$('#password').val();
			if (password=='')
				{
				    alert('请输入密码');
				    return false;
				}
		}
	</script>
<?php echo $this->partial('partials/stats.phtml');?>
</body>
</html>