<div class="header">
	<h1 class="page-title">会员列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/member">会员列表</a></li>
	<?php if ($this->keywords){ ?>
	    <span class="divider">=></span><li class="active">当前搜索关键词：”<?php echo $this->keywords; ?>“</li>
	<?php }?>
		<li style="float: right;"><button class="btn btn-small btn-danger" data-toggle="collapse" data-target="#helpcontroller" onclick="show_help()">[展开/关闭] - 使用帮助</button></li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
    		<div id="helpcontroller" class="collapse"></div>
	<?php 
	if ($this->success)
	{
		echo "<div class=\"alert alert-success\">
        <a class=\"close\" data-dismiss=\"alert\">×</a>
        <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
	}
	?>
		<div class="btn-toolbar">
            <div class="search-well">
                <form class="form-inline" action="" method="post" >
                    <input class="input-xlarge" id="keywords"  name="keywords" type="text" value="<?php echo $this->keywords ;?>" style="margin-right: 5px;">
                    <button class="btn" type="submit" onclick="return checkform();"><i class="icon-search"></i> 搜索</button>
                </form>
            </div>
			<div class="btn-group"><hr></div>
		</div>
        <script src="/lib/bootstrap/js/bootstrap-popover.js" type="text/javascript"></script>
        <script src="/lib/bootstrap/js/bootstrap-tooltip.js" type="text/javascript"></script>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="6%">#</th>
						<th>会员名</th>
						<th>姓名</th>
						<th>Email</th>
						<th>注册时间</th>
						<th>最后登陆时间</th>
						<th>最后登录IP</th>
						<!-- <th style="width: 58px;">改/删</th> -->
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
				    foreach ($this->rows as $val) {
				?>
					<tr id="user_<?php echo $val['id'];?>">
						<td><?php echo $val['id'];?></td>
						<td><?php if($this->keywords){ ?>
						<?php echo str_replace($this->keywords,'<font color=red>'.$this->keywords.'</font>',$val['username']);?>
						<?php }else{ echo $val['username']; }?></td>
						<?php if($this->keywords){ ?>
						<td><?php echo str_replace($this->keywords,'<font color=red>'.$this->keywords.'</font>',$val['realname']);?></td>
						<?php }else{?>
						<td><?php echo $val['realname'];?></td>
						<?php }?>
						<td><?php echo $val['email'];?></td>
						<td><?php echo date("Y-m-d H:i:s",$val['regTime']);?></td>
						<td><?php echo $val['lastTime']?date("Y-m-d",$val['lastTime']):'';?></td>
						<td><?php echo $val['lastIP'];?></td>
						
						<!-- <td>
						<a href="/member/edit?id=<?php echo $val['id'];?>" title="修改编辑"><i class="icon-pencil"></i></a>&nbsp;&nbsp;&nbsp;
						<a href="#myModal" role="button" title="删除" data-toggle="modal" onclick="reid(<?php echo $val['id'];?>);"><i class="icon-remove"></i></a>
						</td> -->
					</tr>
				<?php
				  } 
				}
				?>	
				</tbody>
			</table>
		</div>
		<?php 
		echo $this->paginationcontrol($this->rows,'Sliding','pagination/pagination.phtml',array('key'=>$this->keywords));
		?>
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		   <script type="text/javascript">
           function reid(i){
                 $('#delid').attr('onclick','deluser('+ i +')');
               }
             function deluser(i)
             {
                 $.post('/users/delete?id='+i,{'id':i},function(data){
                     if (data.isok==true)
                     {
                    	 $('#user_'+i).hide();
                     }
                 },'json');
             }
		   </script>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除会员</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>确定删除指定的会员？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="delid" data-dismiss="modal" >确认</button>
			</div>
		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
	</div>
</div>
<script type="text/javascript">
function checkform(){
    var keywords = $('#keywords').val();
    if (keywords == 0 || keywords =='' ) {
        alert('请填写关键词！');
        return false;
    }
}
</script>