<div class="header">
	<h1 class="page-title">编辑分类</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><?php echo $this->bp->genActLink(
		'type_index',
		$this->bp->act_link,
		$this->class_label,
		array(
			'classid'=>$this->row['classid'],
			'route'=>'/t/'
		));?> <span class="divider">/</span></li>
	<li class="active">编辑分类</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
<form id="tab" name="createUser" method="post" action="?id=<?php echo $this->row['id'];?>">
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<input type="hidden" name="classid" value="<?php echo $this->row['classid'];?>" />
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<!-- <ul class="nav nav-tabs">
				<li class="active"><a href="#home" data-toggle="tab">基础配置</a></li>
				<li><a href="#profile" data-toggle="tab">密码设置</a></li>
			</ul> -->
			
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane active in" id="home">
						<div class="control-group" id="group-pid">
							<label class="control-label" for="pid">所属分类</label>
							<div class="controls">
							    <?php echo $this->select_opts;?>
                                <span class="help-inline" id="help-pid"></span>
							</div>
						</div>
						 <div class="control-group" id="group-typeName">
							<label class="control-label" for="typeName">名称</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['name'];?>" id="typeName" name="name" class="input-xlarge">
                                <span class="help-inline" id="help-typeName"></span>
							</div>
						</div>
                        <div class="control-group" id="group-display">
							<label class="control-label" for="display">显示</label>
							<div class="controls">
								是 <input type="radio" value="1" name="display" <?php echo $this->row['display']==1?'checked':'';?> />    
						        否 <input type="radio" value="0" name="display" <?php echo $this->row['display']==0?'checked':'';?> /> 
                                <span class="help-inline" id="help-display"></span>
							</div>
						</div>
						
						<div class="control-group" id="group-aclSorting">
							<label class="control-label" for="aclSorting">排序序号</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['sorting'];?>" id="aclSorting" name="sorting" class="input-xlarge">
                                <span class="help-inline" id="help-aclSorting"></span>
							</div>
						</div>
						
						
				</div>
				<!-- <div class="tab-pane fade" id="profile">
					
						<label>密码</label> <input type="password" name="password" class="input-xlarge">
						<label>确认密码</label> <input type="password" name="repassword" class="input-xlarge">
				</div> -->
			</div>

		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>