<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<meta charset="utf-8" />
	<title><?php echo $this->row['sitename'];?></title>
	<meta name="version" content="游太网络">
	<meta name="author" content="YOUTITLE">
	<meta name="robots" content="all">
	<meta name="copyright" content="Copyright (c) 2013 Youtitle. All Rights Reserved.">
	<meta name="keywords" content="<?php echo $this->row['sitename'];?>">
	<meta name="description" content="<?php echo $this->row['sitename'];?>">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;">
	<meta name="format-detection" content="telephone=no">
	<link type="text/css" rel="stylesheet" href="/css/style.css">
	<link type="text/css" rel="stylesheet" href="/css/comindex.css">
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
	<!--头部-->
	<header class="ts1">
		<ul class="u_home fl">
		  <li><a href="#?ref=footer_index" class="color:#fff"><?php echo $this->row['sitename'];?></a></li>
		</ul>
		<ul class="topbar fr">
			<li><a class="icon_user" href="/user?ref=footer_member"><i></i>我的</a></li>
			<li><a class="icon_class" href="/type?ref=footer_type"><i></i>分类</a></li>
		</ul>
	</header>
	<!--主体-->

<div class="main">
<?php if ($this->hrows) { ?>
    <div class="indexbanner" id="indexbanner">
	   <div class="index-focus" id="indexfocus">
            <ul> 
		<?php
			foreach ($this->hrows as $val) {
				echo "<li><span class=\"car-pic\"><a href=\"/product?id=".$val['id']."\"><img src=\"".$val['thumb']."\"></a></span></li>\n";
			}
		?>
		      </ul>
        </div>
		<h1 class="p_title"></h1>
	</div>
	<div class="index-focus-num" id="index-focus-num">
        <ul><li class="current"></li><li></li><li></li><li></li><li></li>
        </ul>
	</div>
	<?php }?>
	
<div class="searchBanel"> <form method="post" action="/product/search?id=<?php echo $this->id;?>"> <div class="txt" style="position:relative;"> <input type="search" id="keywords" name="keywords" placeholder="请输入商品名称" style="margin-top:2px;height:28px;width:86%;border:0px solid #F1EFF0;background-color:#F1EFF0;line-height:28px;font-size:14px"/> <input type="image" src="images/searchbtn.png" style="position:absolute;right:-13px;top:-1px;height: 33px;" /> </div> </form> </div>
<div class="topicsTab" id="tab1">
    <h2 style="height:32px;">
    <a id="indexnewlink" class="on" onClick="setTabs('indexnew');">最新上线</a>
    <a id="indexcommendlink" class="" onClick="setTabs('indexcommend');">精选推荐</a>
    <a id="indexhotlink" class="" onClick="setTabs('indexhot');">热销排行</a>
    <a style="float:right" href="/product/list">更多</a> 
    </h2>
</div>
<div style="width:100%; float:left; " id="tabtopics">
    <div class="topicss"> 
        <ul class="my_maplist" id="indexnew" style="display: block; ">     
		<?php 
		if ($this->rows)
		{
			foreach ($this->rows as $val) {
		?>
		<li class="zc" data-title="<?php echo $val['name'];?>-<?php echo $val['rebate'];?>">
            <div class="zz">
            <a href="/product?id=<?php echo $val['id'];?>">
            <img data-original="<?php echo BASE_URL.$val['thumb'];?>" src="<?php echo BASE_URL.$val['thumb'];?>" class="lazy" width="100" height="100"><br>
<span><?php echo $val['name'];?> </span><br>
<b class="p"><?php echo $val['rebate'];?>元</b>
</a></div>
            </li>         
		<?php 
		  }
		}
		?>
        </ul>
        <ul class="my_maplist" style="display: none; " id="indexcommend">   
		<?php 
		if ($this->crows)
		{
			foreach ($this->crows as $val) {
		?>
		<li class="zc" data-title="<?php echo $val['name'];?>-<?php echo $val['rebate'];?>">
            <div class="zz">
            <a href="/product?id=<?php echo $val['id'];?>">
            <img data-original="<?php echo BASE_URL.$val['thumb'];?>" src="<?php echo BASE_URL.$val['thumb'];?>" class="lazy" width="100" height="100"><br>
<span><?php echo $val['name'];?> </span><br>
<b class="p"><?php echo $val['rebate'];?>元</b>
</a></div>
            </li>         
		<?php 
		  }
		}
		?>
        </ul>
        <ul class="my_maplist" style="display: none; " id="indexhot">   
		<?php 
		if ($this->trows)
		{
			foreach ($this->trows as $val) {
		?>
		<li class="zc" data-title="<?php echo $val['name'];?>-<?php echo $val['rebate'];?>">
            <div class="zz">
            <a href="/product?id=<?php echo $val['id'];?>">
            <img data-original="<?php echo BASE_URL.$val['thumb'];?>" src="<?php echo BASE_URL.$val['thumb'];?>" class="lazy" width="100" height="100"><br>
<span><?php echo $val['name'];?> </span><br>
<b class="p"><?php echo $val['rebate'];?>元</b>
</a></div>
            </li>         
		<?php 
		  }
		}
		?>
        </ul>
    </div>
</div>
<div class="topicsTab" id="tab2">
    <h2><a>精品分类</a></h2>
    <h2 style="height:32px;float:right"></h2>
</div>
<div class="slideEle column_list ">
                <ul class="category_in">                   
		<?php 
		if ($this->type)
		{
			echo $this->type;
		}
		?> 
                </ul>
</div>


<div class="topicsTab" id="tab2">
  <h2><a>分店导航</a></h2>
    <h2 style="height:32px;float:right"></h2>
</div>
<div class="slideEle column_shop ">
                <ul class="category_shop">                   
		<?php 
		if ($this->shops)
		{
			foreach ($this->shops as $val) {
		?>
                    <li>
                        <a class="font_b red" href="/stores?id=<?php echo $val['id'];?>"><b><?php echo $val['shopname'];?></b></a>                        
                    </li>
		<?php 
		  }
		}
		?> 
                </ul>
</div>
<?php if ($this->row['intro']){ ?>
<div class="comintro"><div class="fbMsg"><a><b>公司简介：</b>&gt;&gt;<br><?php echo $this->row['intro'];?></a></div></div>
<?php }?>
</div>
<?php echo $this->partial ( 'partials/footer.phtml');?>
    <script src="/js/SlideTurnPage.js" type="text/javascript"></script>
    <script>
	function setTabs(xiid){
		var xibie=new Array('indexnew','indexcommend','indexhot');
		var a=null;
		for(var i=0;i<3;i++){
			if(xiid==xibie[i]){
				document.getElementById(xibie[i]).style.display = "block";
				document.getElementById(xibie[i]+'link').className = 'on';
				//$("#"+xibie[i]).find("img[lz_src]").attr("src",function(){var s = $(this).attr("lz_src"); $(this).removeAttr("lz_src"); return s;});
			}else{
				document.getElementById(xibie[i]).style.display = "none";
				document.getElementById(xibie[i]+'link').className = '';
			}
		}
	}
        var slider = new Swipe(document.getElementById('indexfocus'), {
            callback: function (e, pos) {
                var i = bullets.length;
                while (i--) {
                    bullets[i].className = ' ';
                }
                bullets[pos].className = 'current';
            },
            auto: 3000,
            speed: 400
        });
        bullets = document.getElementById('index-focus-num').getElementsByTagName('li');
    </script>
<?php echo $this->partial('partials/stats.phtml');?>
</body>
</html>