<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>VIP客户登记</title>
    <meta name="description" content="唯购" />
    <meta name="keywords" content="唯购" />
    <link href="http://www.veigou.com/css/index1.css" type="text/css" rel="stylesheet" />
    <script src="http://www.veigou.com/js/jquery-1.4.2.zip.js" type="text/javascript"></script>
    <script src="/js/passport.js" type="text/javascript"></script>
</head>
<body class="home">
	<div id="page">
    <!---------------------页面头部及导航开始----------------------->
    <div id="header" class="clearfix">
	<div class="logo">
		<a href="http://www.veigou.com/">LOGO</a>
	</div>
	<div class="info">
		<span><a href="http://www.veigou.com/">唯购首页</a>  |  <a href="http://login.<?php echo $this->host;?>/"> 登陆 </a></span>
	</div>
</div>
    <div id="content" class="clearfix reg-wraper" >
		<div class="reg-nav">
			<ul id="regWays">
                <li class="title">30秒快速注册</li>
                <li data-type="email" class="cur"><a href="javascript:void(0);"><span class="email-icon">商家登记</span></a></li>
			</ul>
		</div>
		<div class="reg-content">
			<div id="step" class="step1"></div>
			<?php
			if ($this->success)
			{
				echo "<div style=\"text-align: center; font-size:14px;padding-top:20px;\">{$this->success->message}</div>";
			}else
			{
			   if ($this->error)
			   {
				   echo "<div style=\"text-align: center; font-size:14px;padding-top:20px;color:red;\">{$this->error->message}</div>"; 
			   }
			?>
			<div id="regWrap">
                <div id="modRegWrap" class="mod-qiuser-pop">
				<form action="" method="post" name="register" onsubmit="return Region.CheckSave();">
                    <dl class="reg-wrap">
                        <dt><span id="regTitle"></span></dt>
                        <dd style="z-index: 10;">
                            <div class="quc-clearfix reg-item">
                                <label for="loginEmail">邮箱</label>
                                <span class="input-bg">
                                    <input name="email" type="text" id="email" maxlength="100" placeholder="请输入邮箱地址" autocomplete="off" class="ipt tipinput" tabindex="1"  onblur="Region.emailValidate();" />
                                </span>
                                <span id="spEmail" class="check"></span>
                            </div>
                        </dd>
						<dd>
                            <div class="quc-clearfix reg-item">
                                <label for="username">用户名</label>
                                <span class="input-bg">
                                    <input name="username" type="text" id="username" maxlength="20" placeholder="请输入登陆名/域名(字母开头)" autocomplete="off" class="ipt tipinput" tabindex="2" onblur="Region.userNameValidate();" />
                                </span>
                                <span id="spUserName" class="check"></span>
                            </div>
                               <!-- <label for="remark">备注：用户名就是域名，请以英文开头，不含特殊字符、空格等，长度大于等于6</label> --> 
                        </dd>
                        <dd>
                            <div class="quc-clearfix reg-item">
                                <label for="password">密码</label>
                                <span class="input-bg">
                                    <input name="password" type="password" id="txtPwd" maxlength="20" placeholder="请输入登陆密码（6-20位字符）" autocomplete="off" class="ipt tipinput" tabindex="2" onblur="Region.PwdValidate();Region.ConfirmPwd();" />
                                </span>
                                <span id="spPwd" class="check"></span>
                            </div>
                        </dd>
                        <dd>
                            <div class="quc-clearfix reg-item">
                                <label for="rePassword">确认密码</label>
                                <span class="input-bg">
                                    <input name="repassword" type="password" id="txtConfirmPwd" placeholder="请再次输入密码" autocomplete="off" class="ipt tipinput" tabindex="3" maxlength="20" onblur="Region.PwdValidate();Region.ConfirmPwd();" />
                                </span>
                                <span class="check" id="spConfirmPwd"></span>
                            </div>
                        </dd>
                        <dd>
                            <div class="quc-clearfix reg-item">
                                <label for="companyName">企业名称</label>
                                <span class="input-bg">
                                    <input name="realname" type="text" id="txtCompanyName" maxlength="50" placeholder="请填写您的企业名称" autocomplete="off" class="ipt tipinput" tabindex="4" onblur="Region.ComNameValidate();" />
                                </span>
                                <span id="spCompanyName" class="check"></span>
                            </div>
                        </dd>
                        <dd>
                            <div class="quc-clearfix reg-item">
                                <label for="mobile">手机号码</label>
                                <span class="input-bg">
                                    <input name="tel" type="text" id="txtMobile" maxlength="15" placeholder="请填写联系人手机" autocomplete="off" class="ipt tipinput" tabindex="6" onkeyup="value=value.replace(/[^\d]/g,'');" onblur="Region.MobileValidate();" />
                                </span>
                                <span id="spMobile" class="check"></span>
                            </div>
                        </dd>                        
                       
                        <dd class="submit">
                            <input type="submit" name="btnRegist" value="" id="btnRegist" class="btn-register" />
                        </dd>
                        <dd class="rules">
                            <label style="" for="is_agree"><input type="checkbox" name="is_agree" id="is_agree" tabindex="5" checked="checked" value="1" /> 我已经阅读并同意</label>
                            <a href="#" class="fac">《用户服务条款》</a>
                            <div class="reg-global-error">
                                <!--操作结果提示-->
                                
                                
                            </div>
                        </dd>
                    </dl>
                </form>
				</div>
			</div>
			<?php
			}
			?>
		</div></div>
	</div>
    <div class="clear"></div>
<script src="http://www.veigou.com/js/footer.js" type="text/javascript"></script>
</body>
</html>