<div class="header">
	<h1 class="page-title">添加商品属性</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/t/?classid=<?php echo $this->prodClassInfo->classid?>"><?php echo $this->prodClassInfo->name;?>(商品分类)</a> <span class="divider">/</span></li>
	<li><a href="/attribute/?prod_class=<?php echo $this->prodClassInfo->id?>">商品属性列表</a> <span class="divider">/</span></li>
	
	<li class="active">编辑商品属性</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
<form id="tab" name="createType" method="post" action="" onsubmit="return clickType();">
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<input type="hidden" name="prod_class" value="<?php echo $this->prodClassInfo->id;?>">
			<div class="btn-group"></div>
		</div>
		<div class="well">
			
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane active in" id="home">
				       <div class="control-group" id="group-pid">
							<label class="control-label" for="pid">所属上级属性</label>
							<div class="controls">
							    <?php echo $this->select_opts;?>
                                <span class="help-inline" id="help-pid"></span>
							</div>
						</div>
						 <div class="control-group" id="group-typeName">
							<label class="control-label" for="typeName">属性名称</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['name']?>" id="typeName" name="name" class="input-xlarge">
                                <span class="help-inline" id="help-typeName"></span>
							</div>
						</div>
						
                        <div class="control-group" id="group-display">
							<label class="control-label" for="display">显示</label>
							<div class="controls">
								是 <input type="radio" value="1" name="display" <?php echo $this->row['display']==1?'checked':'';?> />    
						        否 <input type="radio" value="0" name="display" <?php echo $this->row['display']==0?'checked':'';?> /> 
                                <span class="help-inline" id="help-display"></span>
							</div>
						</div>
						
						<div class="control-group" id="group-aclSorting">
							<label class="control-label" for="aclSorting">排序序号</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['sorting'];?>" id="aclSorting" name="sorting" class="input-xlarge">
                                <span class="help-inline" id="help-aclSorting"></span>
							</div>
						</div>
						
				</div>
			</div>

		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>