<div class="header">
	<h1 class="page-title">商品属性列表</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/t/?classid=<?php echo $this->prodClassInfo->classid?>"><?php echo $this->prodClassInfo->name;?>(商品分类)</a> <span class="divider">/</span></li>
	<li class="active">商品属性列表</li>
</ul>

<div class="container-fluid">
	<?php echo $this->partial('partials/flashMsg.phtml');?>
	<div class="row-fluid">
		<div class="btn-toolbar">
			<?php echo $this->bp->genActLink(
				'attribute_create',
				$this->bp->act_add,
				'添加属性',
				array(
					'prod_class'=>$this->prodClassInfo->id,
				));
			?>
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>属性名称</th>
						<th>是否显示</th>
						<th>排序序号</th>
						<th style="width: 50px;">改/删</th>
					</tr>
				</thead>
				<tbody>
				
				
				<?php 
					if($this->rows):
						foreach($this->rows as $val):
				?>
						<tr id="type_<?php echo $val['id'];?>">
							<td><?php echo $val['id'];?></td>
							<td><?php echo $val['name'];?></td>
							<td><?php echo $val['display']==1?'显示':'隐藏';?></td>
							<td>
							<input type="text" id="s_<?php echo $val['id']?>" value="<?php echo $val['sorting'];?>" class="input-mini">
							<a href="#" class="to_sorting" id="lk_<?php echo $val['id'];?>">更新排序</a>
							</td>
							<td>
							<?php echo $this->bp->genActLink(
								'attribute_edit',
								$this->bp->act_edit,
								'',
								array(
									'id'=>$val['id']
								));?>
							 &nbsp;
							<?php echo $this->bp->genActLink('attribute_delete',$this->bp->act_del,'',array('del_id'=>$val['id']));?>
							</td>
						</tr>
				<?php	
						endforeach; 
					endif;
				?>
				
				
				
				<!--Display List-->	
				</tbody>
			</table>
		</div>
		
		<?php
		if($this->pager_link){
			echo $this->pager_link;
		}
		?>
		
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<script type="text/javascript">
		
		
		function triggerDel(del_id)
	    {
	   		$("#remove").click(function(){
				
				
				/*$.post('/attribute/delete?id='+del_id,{'id':del_id},function(data){
                     alert(data.msg);
					 if (data.req=="ok")
                     {
						 window.location.reload();
                     }
                 },'json');*/
				 
				 //这种方式更简单
				 $.getJSON('/attribute/delete?id='+del_id,function(data){
				 	alert(data.msg);
					if(data.req == "ok"){
						window.location.reload();
					}
				 });
				
			});		
	    }
		
		$(document).ready(function(){
	   		$("a.to_sorting").click(function(){
				var this_id = this.id;
				var obj_id = this_id.replace("lk","s");
				var sorting = parseInt($("#"+obj_id).val());
				var id = parseInt(this_id.replace("lk_",""));
				$.post('/attribute/ajaxUpdateSorting?id='+id+'&sorting='+sorting,{},function(data){
                    alert(data.msg);
					if(data.req == "ok"){
						window.location.reload();
					}
                 },'json');
			});	
	   });
			   
		   </script>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除商品属性</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>是否删除选定的商品属性？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="remove" data-dismiss="modal">确定</button>
			</div>
		</div>
		<?php 
		echo $this->partial('partials/homeFooter.phtml');
		?>
	</div>
</div>